#include "CodeEditorWidget.h"
#include "CodeEditorTab.h"
#include "CompletionPopup.h"
#include "FindReplaceBar.h"
#include "BuildManager.h"
#include "AnnotationParser.h"
#include "ModuleEditorWidget.h"
#include "../lsp/LSPClient.h"
#include "../core/ModuleRegistry.h"

#include <QFileInfo>
#include <QMessageBox>
#include <QInputDialog>
#include <QFile>
#include <QJsonDocument>
#include <QToolTip>
#include <QPlainTextEdit>
#include <QPushButton>
#include <QLabel>
#include <QHBoxLayout>
#include <QTextCursor>
#include <QRegularExpression>

namespace DeltaQ {

namespace {

struct GeneratedFileInfo {
    bool isGenerated = false;
    QString sourceLine;
    QString roleLine;
    QString sourceKind;
    QString sourceName;
    QString sourceId;
};

// Разбирает banner generated-файла и извлекает данные о source-of-truth.
GeneratedFileInfo inspectGeneratedFile(const QString &text)
{
    GeneratedFileInfo info;
    const QStringList lines = text.split('\n');
    if (lines.isEmpty())
        return info;

    if (!lines.first().contains("Generated by DeltaQ IDE."))
        return info;

    info.isGenerated = true;
    for (const auto &line : lines.mid(1, 3)) {
        if (line.startsWith("// Source: ")) {
            info.sourceLine = line.mid(3);
            static const QRegularExpression sourceRx(
                "^// Source: (graph|UI layout) '([^']+)'(?: \\(id: ([^)]+)\\))?$");
            const auto match = sourceRx.match(line);
            if (match.hasMatch()) {
                info.sourceKind = match.captured(1);
                info.sourceName = match.captured(2);
                info.sourceId = match.captured(3);
            }
        } else if (line.startsWith("// File role: ")) {
            info.roleLine = line.mid(3);
        }
    }
    return info;
}

// Возвращает LSP language id по файловому расширению исходника.
QString languageIdForPath(const QString &path)
{
    if (path.endsWith(".h") || path.endsWith(".hpp"))
        return QStringLiteral("cpp");
    if (path.endsWith(".c"))
        return QStringLiteral("c");
    return QStringLiteral("cpp");
}

// Формирует заголовок вкладки с учётом generated-статуса и модификации.
QString makeTabTitle(const CodeEditorTab *tab)
{
    QString title = QFileInfo(tab->filePath()).fileName();
    if (tab->property("deltaqGenerated").toBool())
        title += " [gen]";
    if (tab->isModified())
        title += " *";
    return title;
}

// Показывает во всплывающей подсказке, что файл generated и откуда он получен.
QString makeTabToolTip(const CodeEditorTab *tab)
{
    QString toolTip = tab->filePath();
    if (!tab->property("deltaqGenerated").toBool())
        return toolTip;

    toolTip += "\nGenerated by DeltaQ IDE";
    toolTip += "\nRead-only generated file";
    const QString sourceLine = tab->property("deltaqGeneratedSource").toString();
    const QString roleLine = tab->property("deltaqGeneratedRole").toString();
    if (!sourceLine.isEmpty())
        toolTip += "\n" + sourceLine;
    if (!roleLine.isEmpty())
        toolTip += "\n" + roleLine;
    toolTip += "\nEdit the source-of-truth instead.";
    return toolTip;
}

// Проверяет, относится ли вкладка к generated-артефактам DeltaQ.
bool isGeneratedTab(const CodeEditorTab *tab)
{
    return tab && tab->property("deltaqGenerated").toBool();
}

// Строит короткий текст для inline-баннера над generated-вкладкой.
QString makeGeneratedBannerText(const CodeEditorTab *tab)
{
    if (!isGeneratedTab(tab))
        return {};

    QString sourceText;
    const QString sourceKind = tab->property("deltaqGeneratedSourceKind").toString();
    const QString sourceName = tab->property("deltaqGeneratedSourceName").toString();
    const QString sourceId = tab->property("deltaqGeneratedSourceId").toString();

    if (!sourceKind.isEmpty() && !sourceName.isEmpty()) {
        sourceText = QObject::tr("Source of truth: %1 '%2'")
                         .arg(sourceKind, sourceName);
        if (!sourceId.isEmpty())
            sourceText += QObject::tr(" (id: %1)").arg(sourceId);
    } else {
        sourceText = tab->property("deltaqGeneratedSource").toString();
    }

    if (sourceText.isEmpty())
        sourceText = QObject::tr("Generated output tracked by DeltaQ.");

    return QObject::tr("Read-only generated file. %1").arg(sourceText);
}

// Синхронизирует заголовок и tooltip вкладки после смены её состояния.
void updateTabPresentation(QTabWidget *tabWidget, CodeEditorTab *tab)
{
    const int idx = tabWidget->indexOf(tab);
    if (idx < 0)
        return;
    tabWidget->setTabText(idx, makeTabTitle(tab));
    tabWidget->setTabToolTip(idx, makeTabToolTip(tab));
}

QString makeCustomTabTitle(QWidget *widget, const QString &fallbackTitle)
{
    if (auto *moduleEditor = qobject_cast<ModuleEditorWidget *>(widget))
        return moduleEditor->tabTitle();
    return fallbackTitle;
}

} // namespace

CodeEditorWidget::CodeEditorWidget(CommandBus *bus, ModuleRegistry *registry,
                                     QWidget *parent)
    : QWidget(parent)
    , m_commandBus(bus)
    , m_moduleRegistry(registry)
    , m_annotationParser(new AnnotationParser(this))
{
    auto *layout = new QVBoxLayout(this);
    layout->setContentsMargins(0, 0, 0, 0);

    m_tabWidget = new QTabWidget(this);
    m_tabWidget->setTabsClosable(true);
    m_tabWidget->setMovable(true);
    m_tabWidget->setDocumentMode(true);
    layout->addWidget(m_tabWidget);

    m_generatedBanner = new QWidget(this);
    m_generatedBanner->setObjectName("generatedOriginBanner");
    m_generatedBanner->setStyleSheet(
        "QWidget#generatedOriginBanner {"
        " background-color: #f6ecd1;"
        " border: 1px solid #d7bf7d;"
        " border-radius: 4px;"
        "}"
    );
    auto *bannerLayout = new QHBoxLayout(m_generatedBanner);
    bannerLayout->setContentsMargins(10, 6, 10, 6);
    bannerLayout->setSpacing(8);

    m_generatedBannerLabel = new QLabel(m_generatedBanner);
    m_generatedBannerLabel->setObjectName("generatedOriginLabel");
    m_generatedBannerLabel->setWordWrap(true);
    bannerLayout->addWidget(m_generatedBannerLabel, 1);

    m_generatedBannerButton = new QPushButton(tr("Open Origin"), m_generatedBanner);
    m_generatedBannerButton->setObjectName("generatedOriginButton");
    bannerLayout->addWidget(m_generatedBannerButton, 0, Qt::AlignRight);
    m_generatedBanner->hide();
    layout->addWidget(m_generatedBanner);

    // Панель поиска и замены (под вкладками)
    m_findBar = new FindReplaceBar(this);
    layout->addWidget(m_findBar);

    connect(m_tabWidget, &QTabWidget::tabCloseRequested, this, &CodeEditorWidget::closeTab);
    connect(m_tabWidget, &QTabWidget::currentChanged, this, &CodeEditorWidget::onTabChanged);
    connect(m_generatedBannerButton, &QPushButton::clicked,
            this, &CodeEditorWidget::openGeneratedOriginRequested);
}

void CodeEditorWidget::closeAllTabs()
{
    while (m_tabWidget->count() > 0)
        closeTab(0);
}

void CodeEditorWidget::openFile(const QString &path)
{
    // Check if already open
    auto *existing = findTabForFile(path);
    if (existing) {
        m_tabWidget->setCurrentWidget(existing);
        return;
    }

    auto *tab = new CodeEditorTab(path, m_commandBus, this);
    if (!tab->loadFile(path)) {
        delete tab;
        QMessageBox::warning(this, tr("Error"),
                             tr("Cannot open file: %1").arg(path));
        return;
    }

    QFileInfo fi(path);
    int index = m_tabWidget->addTab(tab, fi.fileName());
    m_tabWidget->setCurrentIndex(index);
    m_openFiles[path] = index;

    // Сразу после загрузки определяем, является ли файл generated-артефактом.
    const GeneratedFileInfo generatedInfo = inspectGeneratedFile(tab->editor()->toPlainText());
    tab->setProperty("deltaqGenerated", generatedInfo.isGenerated);
    tab->setProperty("deltaqGeneratedSource", generatedInfo.sourceLine);
    tab->setProperty("deltaqGeneratedRole", generatedInfo.roleLine);
    tab->setProperty("deltaqGeneratedSourceKind", generatedInfo.sourceKind);
    tab->setProperty("deltaqGeneratedSourceName", generatedInfo.sourceName);
    tab->setProperty("deltaqGeneratedSourceId", generatedInfo.sourceId);
    tab->editor()->setReadOnly(generatedInfo.isGenerated);
    updateTabPresentation(m_tabWidget, tab);
    updateGeneratedOriginBanner();

    // Подключаем сигналы вкладки
    connectTabSignals(tab);

    // LSP: уведомляем сервер об открытии файла
    if (m_lspClient && m_lspClient->isRunning()) {
        QString uri = LSPClient::pathToUri(path);
        QString langId = languageIdForPath(path);
        m_documentVersions[uri] = 1;
        m_lspClient->didOpen(uri, langId, tab->editor()->toPlainText());

        // Подключаем отправку изменений при редактировании
        connect(tab->editor()->document(), &QTextDocument::contentsChanged, this, [this, tab]() {
            if (!m_lspClient || !m_lspClient->isRunning())
                return;
            QString uri = LSPClient::pathToUri(tab->filePath());
            int &ver = m_documentVersions[uri];
            ++ver;
            m_lspClient->didChange(uri, ver, tab->editor()->toPlainText());
        });
    }

    connect(tab, &CodeEditorTab::modificationChanged, this, [this, tab](bool modified) {
        Q_UNUSED(modified)
        updateTabPresentation(m_tabWidget, tab);
    });

    // Повторно уведомляем MainWindow уже после установки generated/read-only metadata.
    emit currentTabChanged();
}

// Подключает все сигналы вкладки к LSP и общим действиям редактора.
void CodeEditorWidget::connectTabSignals(CodeEditorTab *tab)
{
    // Hover: tab → LSPClient → tab
    connect(tab, &CodeEditorTab::hoverRequested,
            this, [this](const QString &filePath, int line, int character) {
        if (!m_lspClient || !m_lspClient->isRunning()) return;
        QString uri = LSPClient::pathToUri(filePath);
        m_lspClient->hover(uri, line, character);
    });

    // Completion: tab → LSPClient
    connect(tab, &CodeEditorTab::completionRequested,
            this, [this](const QString &filePath, int line, int character) {
        if (!m_lspClient || !m_lspClient->isRunning()) return;
        QString uri = LSPClient::pathToUri(filePath);
        m_lspClient->completion(uri, line, character);
    });

    // Breakpoint: tab → MainWindow (через сигнал)
    connect(tab, &CodeEditorTab::breakpointToggleRequested,
            this, &CodeEditorWidget::breakpointToggleRequested);

    // Вставка текста из popup автодополнения
    if (tab->completionPopup()) {
        connect(tab->completionPopup(), &CompletionPopup::itemSelected,
                this, [tab](const QString &text) {
            QTextCursor cursor = tab->editor()->textCursor();
            // Удаляем слово перед курсором и вставляем выбранное
            cursor.select(QTextCursor::WordUnderCursor);
            cursor.insertText(text);
        });
    }
}

// Подключает dedicated module editor к тем же LSP/document lifecycle, что и обычные code tabs.
void CodeEditorWidget::connectModuleEditorSignals(ModuleEditorWidget *moduleEditor)
{
    if (!moduleEditor)
        return;

    connect(moduleEditor->editor()->document(), &QTextDocument::contentsChanged, this, [this, moduleEditor]() {
        if (!m_lspClient || !m_lspClient->isRunning())
            return;

        const QString documentPath = moduleEditor->lspDocumentPath();
        if (documentPath.isEmpty())
            return;

        const QString uri = LSPClient::pathToUri(documentPath);
        int &version = m_documentVersions[uri];
        if (version <= 0)
            version = 1;
        ++version;
        m_lspClient->didChange(uri, version, moduleEditor->sourceText());
    });

    connect(moduleEditor, &ModuleEditorWidget::hoverRequested, this,
            [this](const QString &documentPath, int line, int character) {
        if (!m_lspClient || !m_lspClient->isRunning())
            return;
        m_lspClient->hover(LSPClient::pathToUri(documentPath), line, character);
    });

    connect(moduleEditor, &ModuleEditorWidget::completionRequested, this,
            [this](const QString &documentPath, int line, int character) {
        if (!m_lspClient || !m_lspClient->isRunning())
            return;
        m_lspClient->completion(LSPClient::pathToUri(documentPath), line, character);
    });

    if (m_lspClient && m_lspClient->isRunning()) {
        const QString documentPath = moduleEditor->lspDocumentPath();
        if (!documentPath.isEmpty()) {
            const QString uri = LSPClient::pathToUri(documentPath);
            m_documentVersions[uri] = 1;
            m_lspClient->didOpen(uri, moduleEditor->lspLanguageId(), moduleEditor->sourceText());
        }
    }
}

void CodeEditorWidget::saveCurrentFile()
{
    auto *tab = currentTab();
    if (tab) {
        // Generated-файлы считаются только результатом pre-build и не сохраняются вручную.
        if (tab->property("deltaqGenerated").toBool())
            return;

        tab->saveFile();
        // LSP: уведомляем о сохранении
        if (m_lspClient && m_lspClient->isRunning())
            m_lspClient->didSave(LSPClient::pathToUri(tab->filePath()));

        // Автогенерация .dqmod из аннотаций
        parseAndSaveModules(tab->filePath());

        emit fileSaved(tab->filePath());
    }
}

void CodeEditorWidget::parseAndSaveModules(const QString &filePath)
{
    // Парсим только C/C++ файлы
    if (!filePath.endsWith(".c") && !filePath.endsWith(".cpp") &&
        !filePath.endsWith(".cxx") && !filePath.endsWith(".cc") &&
        !filePath.endsWith(".h") && !filePath.endsWith(".hpp"))
        return;

    auto modules = m_annotationParser->parseFile(filePath);
    if (modules.isEmpty())
        return;

    // Сохраняем каждый модуль как .dqmod и регистрируем в реестре
    for (const auto &mod : modules) {
        // Сохраняем .dqmod рядом с исходником
        QString dqmodPath = AnnotationParser::dqmodPathForSource(filePath);
        if (modules.size() > 1) {
            // Несколько модулей в одном файле — добавляем имя модуля в путь
            QFileInfo fi(filePath);
            dqmodPath = fi.absolutePath() + "/" + mod.name + ".dqmod";
        }

        QFile file(dqmodPath);
        if (file.open(QIODevice::WriteOnly)) {
            QJsonDocument doc(mod.toJson());
            file.write(doc.toJson(QJsonDocument::Indented));
        }

        // Регистрируем/обновляем в реестре
        if (m_moduleRegistry)
            m_moduleRegistry->registerModule(mod);
    }
}

bool CodeEditorWidget::hasUnsavedChanges() const
{
    for (int i = 0; i < m_tabWidget->count(); ++i) {
        auto *tab = qobject_cast<CodeEditorTab *>(m_tabWidget->widget(i));
        if (tab && tab->isModified())
            return true;
        auto *moduleEditor = qobject_cast<ModuleEditorWidget *>(m_tabWidget->widget(i));
        if (moduleEditor && moduleEditor->hasUnsavedChanges())
            return true;
    }
    return false;
}

void CodeEditorWidget::buildProject(const QString &projectDir)
{
    emit buildRequested(projectDir);
}

CodeEditorTab *CodeEditorWidget::currentTab() const
{
    return qobject_cast<CodeEditorTab *>(m_tabWidget->currentWidget());
}

// Возвращает активный текстовый редактор как для обычных файлов, так и для `.dqmod` surface.
QPlainTextEdit *CodeEditorWidget::currentPlainTextEditor() const
{
    if (auto *tab = currentTab())
        return tab->editor();
    if (auto *moduleEditor = qobject_cast<ModuleEditorWidget *>(currentCustomTabWidget()))
        return moduleEditor->editor();
    return nullptr;
}

// Возвращает путь активного документа, независимо от того, это code tab или `.dqmod` editor.
QString CodeEditorWidget::currentFilePath() const
{
    if (auto *tab = currentTab())
        return tab->filePath();
    if (auto *moduleEditor = qobject_cast<ModuleEditorWidget *>(currentCustomTabWidget()))
        return moduleEditor->filePath();
    return {};
}

// Возвращает путь документа, который следует использовать для LSP над активной вкладкой.
QString CodeEditorWidget::currentLspDocumentPath() const
{
    if (auto *tab = currentTab())
        return tab->filePath();
    if (auto *moduleEditor = qobject_cast<ModuleEditorWidget *>(currentCustomTabWidget()))
        return moduleEditor->lspDocumentPath();
    return {};
}

// Возвращает language id активного документа для LSP document sync.
QString CodeEditorWidget::currentLspLanguageId() const
{
    if (auto *tab = currentTab())
        return languageIdForPath(tab->filePath());
    if (auto *moduleEditor = qobject_cast<ModuleEditorWidget *>(currentCustomTabWidget()))
        return moduleEditor->lspLanguageId();
    return {};
}

QStringList CodeEditorWidget::openFilePaths() const
{
    QStringList paths;
    for (int i = 0; i < m_tabWidget->count(); ++i) {
        auto *tab = qobject_cast<CodeEditorTab *>(m_tabWidget->widget(i));
        if (tab)
            paths.append(tab->filePath());
    }
    return paths;
}

void CodeEditorWidget::closeTab(int index)
{
    QWidget *widget = m_tabWidget->widget(index);
    if (!widget) return;

    // Кастомная вкладка (граф, UI-макет)
    auto *tab = qobject_cast<CodeEditorTab *>(widget);
    if (!tab) {
        if (auto *moduleEditor = qobject_cast<ModuleEditorWidget *>(widget)) {
            if (moduleEditor->hasUnsavedChanges()) {
                const auto result = QMessageBox::question(
                    this,
                    tr("Save Module"),
                    tr("Save changes to %1?").arg(QFileInfo(moduleEditor->filePath()).fileName()),
                    QMessageBox::Save | QMessageBox::Discard | QMessageBox::Cancel);
                if (result == QMessageBox::Cancel)
                    return;
                if (result == QMessageBox::Save && !moduleEditor->saveModule())
                    return;
            }

            if (m_lspClient && m_lspClient->isRunning()) {
                const QString documentPath = moduleEditor->lspDocumentPath();
                if (!documentPath.isEmpty()) {
                    const QString uri = LSPClient::pathToUri(documentPath);
                    m_lspClient->didClose(uri);
                    m_documentVersions.remove(uri);
                }
            }
        }

        // Удаляем из m_customTabs
        for (auto it = m_customTabs.begin(); it != m_customTabs.end(); ++it) {
            if (it.value() == widget) {
                m_customTabs.erase(it);
                break;
            }
        }
        m_tabWidget->removeTab(index);
        delete widget;
        return;
    }

    if (tab->isModified()) {
        auto result = QMessageBox::question(this, tr("Save Changes"),
            tr("Save changes to %1?").arg(QFileInfo(tab->filePath()).fileName()),
            QMessageBox::Save | QMessageBox::Discard | QMessageBox::Cancel);

        if (result == QMessageBox::Cancel)
            return;
        if (result == QMessageBox::Save)
            tab->saveFile();
    }

    // LSP: уведомляем о закрытии документа
    if (m_lspClient && m_lspClient->isRunning()) {
        QString uri = LSPClient::pathToUri(tab->filePath());
        m_lspClient->didClose(uri);
        m_documentVersions.remove(uri);
    }

    m_openFiles.remove(tab->filePath());
    m_tabWidget->removeTab(index);
    delete tab;

    // Update indices
    m_openFiles.clear();
    for (int i = 0; i < m_tabWidget->count(); ++i) {
        auto *t = qobject_cast<CodeEditorTab *>(m_tabWidget->widget(i));
        if (t)
            m_openFiles[t->filePath()] = i;
    }
}

void CodeEditorWidget::onTabChanged(int /*index*/)
{
    // Обновляем редактор в панели поиска при смене вкладки
    m_findBar->setEditor(currentPlainTextEditor());
    updateGeneratedOriginBanner();
    emit currentTabChanged();
}

void CodeEditorWidget::updateGeneratedOriginBanner()
{
    auto *tab = currentTab();
    if (!isGeneratedTab(tab)) {
        m_generatedBanner->hide();
        m_generatedBannerLabel->clear();
        m_generatedBannerButton->setEnabled(false);
        return;
    }

    // Баннер выводит источник generated-файла и даёт быстрый переход к нему.
    m_generatedBannerLabel->setText(makeGeneratedBannerText(tab));
    const bool hasOrigin =
        !tab->property("deltaqGeneratedSourceKind").toString().isEmpty() &&
        !tab->property("deltaqGeneratedSourceName").toString().isEmpty();
    m_generatedBannerButton->setEnabled(hasOrigin);
    m_generatedBannerButton->setVisible(hasOrigin);
    m_generatedBanner->show();
}

void CodeEditorWidget::setLSPClient(LSPClient *client)
{
    m_lspClient = client;

    if (!m_lspClient) return;

    // Hover-результат → показываем подсказку
    connect(m_lspClient, &LSPClient::hoverResult, this, [this](const HoverInfo &info) {
        if (info.contents.isEmpty()) return;

        const QPoint globalPos = QCursor::pos();
        if (auto *tab = currentTab()) {
            tab->showHoverTooltip(info.contents, globalPos);
            return;
        }
        if (auto *moduleEditor = qobject_cast<ModuleEditorWidget *>(currentCustomTabWidget()))
            moduleEditor->showHoverTooltip(info.contents, globalPos);
    });

    // Completion-результат → показываем popup
    connect(m_lspClient, &LSPClient::completionResult, this,
            [this](const QVector<CompletionItem> &items) {
        if (auto *tab = currentTab()) {
            tab->showCompletion(items);
            return;
        }
        if (auto *moduleEditor = qobject_cast<ModuleEditorWidget *>(currentCustomTabWidget()))
            moduleEditor->showCompletion(items);
    });

    // Rename-результат → применяем правки
    connect(m_lspClient, &LSPClient::renameResult, this,
            [this](const WorkspaceEdit &edits) {
        for (auto it = edits.changes.begin(); it != edits.changes.end(); ++it) {
            QString path = LSPClient::uriToPath(it.key());
            auto *editor = findOpenPlainTextEditorForDocumentPath(path);
            if (!editor && findTabForFile(path) == nullptr && findOpenModuleEditorForDocumentPath(path) == nullptr) {
                openFile(path);
                editor = findOpenPlainTextEditorForDocumentPath(path);
            }
            if (!editor)
                continue;
            applyTextEdits(editor, it.value());
        }
    });

    // Formatting-результат → применяем правки
    connect(m_lspClient, &LSPClient::formattingResult, this,
            [this](const QVector<LSPTextEdit> &edits) {
        applyTextEdits(currentPlainTextEditor(), edits);
    });

    // Diagnostics-уведомления всегда живут в editor layer, а не только в MainWindow wiring.
    connect(m_lspClient, &LSPClient::diagnosticsReceived,
            this, &CodeEditorWidget::onDiagnosticsReceived);
}

void CodeEditorWidget::goToDefinition()
{
    if (!m_lspClient || !m_lspClient->isRunning())
        return;
    auto *editor = currentPlainTextEditor();
    const QString documentPath = currentLspDocumentPath();
    if (!editor || documentPath.isEmpty())
        return;

    auto cursor = editor->textCursor();
    QString uri = LSPClient::pathToUri(documentPath);
    m_lspClient->definition(uri, cursor.blockNumber(), cursor.columnNumber());
}

void CodeEditorWidget::findReferences()
{
    if (!m_lspClient || !m_lspClient->isRunning())
        return;
    auto *editor = currentPlainTextEditor();
    const QString documentPath = currentLspDocumentPath();
    if (!editor || documentPath.isEmpty())
        return;

    auto cursor = editor->textCursor();
    QString uri = LSPClient::pathToUri(documentPath);
    m_lspClient->references(uri, cursor.blockNumber(), cursor.columnNumber());
}

void CodeEditorWidget::renameSymbol()
{
    if (!m_lspClient || !m_lspClient->isRunning())
        return;
    auto *editor = currentPlainTextEditor();
    const QString documentPath = currentLspDocumentPath();
    if (!editor || documentPath.isEmpty())
        return;
    if (editor->isReadOnly())
        return;

    auto cursor = editor->textCursor();
    cursor.select(QTextCursor::WordUnderCursor);
    QString oldName = cursor.selectedText();

    bool ok = false;
    QString newName = QInputDialog::getText(this, tr("Rename Symbol"),
        tr("New name:"), QLineEdit::Normal, oldName, &ok);

    if (!ok || newName.isEmpty() || newName == oldName)
        return;

    QString uri = LSPClient::pathToUri(documentPath);
    m_lspClient->rename(uri, cursor.blockNumber(),
                        editor->textCursor().columnNumber(), newName);
}

void CodeEditorWidget::formatDocument()
{
    if (!m_lspClient || !m_lspClient->isRunning())
        return;
    auto *editor = currentPlainTextEditor();
    const QString documentPath = currentLspDocumentPath();
    if (!editor || documentPath.isEmpty())
        return;
    if (editor->isReadOnly())
        return;

    QString uri = LSPClient::pathToUri(documentPath);
    m_lspClient->formatting(uri);
}

void CodeEditorWidget::onDiagnosticsReceived(const QString &uri,
                                              const QVector<LSPDiagnostic> &diagnostics)
{
    QString path = LSPClient::uriToPath(uri);
    auto *tab = findTabForFile(path);
    if (tab) {
        tab->setDiagnostics(diagnostics);
    } else if (auto *moduleEditor = findOpenModuleEditorForDocumentPath(path)) {
        moduleEditor->setDiagnostics(diagnostics);
    }

    // Подсчитываем ошибки/предупреждения для ProjectTreeView
    int errors = 0, warnings = 0;
    for (const auto &d : diagnostics) {
        if (d.severity == DiagnosticSeverity::Error) ++errors;
        else if (d.severity == DiagnosticSeverity::Warning) ++warnings;
    }
    emit diagnosticsUpdated(path, errors, warnings);
}

void CodeEditorWidget::clearDebugLineInAllTabs()
{
    for (int i = 0; i < m_tabWidget->count(); ++i) {
        auto *tab = qobject_cast<CodeEditorTab *>(m_tabWidget->widget(i));
        if (tab)
            tab->clearDebugCurrentLine();
    }
}

void CodeEditorWidget::showFind()
{
    if (auto *editor = currentPlainTextEditor()) {
        m_findBar->setEditor(editor);
        m_findBar->showFind();
    }
}

void CodeEditorWidget::showReplace()
{
    if (auto *editor = currentPlainTextEditor()) {
        m_findBar->setEditor(editor);
        m_findBar->showReplace();
    }
}

void CodeEditorWidget::goToLine()
{
    auto *editor = currentPlainTextEditor();
    if (!editor)
        return;
    int maxLine = editor->blockCount();
    bool ok = false;
    int line = QInputDialog::getInt(this, tr("Go to Line"),
        tr("Line number (1–%1):").arg(maxLine),
        editor->textCursor().blockNumber() + 1,
        1, maxLine, 1, &ok);

    if (ok) {
        QTextCursor cursor(editor->document()->findBlockByNumber(line - 1));
        editor->setTextCursor(cursor);
        editor->centerCursor();
        editor->setFocus();
    }
}

// Ищет уже открытую module-вкладку по document path, через который она синхронизируется с LSP.
ModuleEditorWidget *CodeEditorWidget::findOpenModuleEditorForDocumentPath(const QString &path) const
{
    for (int i = 0; i < m_tabWidget->count(); ++i) {
        auto *moduleEditor = qobject_cast<ModuleEditorWidget *>(m_tabWidget->widget(i));
        if (!moduleEditor)
            continue;
        if (moduleEditor->lspDocumentPath() == path || moduleEditor->filePath() == path)
            return moduleEditor;
    }
    return nullptr;
}

// Возвращает текстовый редактор по document path для обычных и module-вкладок.
QPlainTextEdit *CodeEditorWidget::findOpenPlainTextEditorForDocumentPath(const QString &path) const
{
    if (auto *tab = findTabForFile(path))
        return tab->editor();
    if (auto *moduleEditor = findOpenModuleEditorForDocumentPath(path))
        return moduleEditor->editor();
    return nullptr;
}

// Применяет набор LSP text edits в обратном порядке, чтобы позиции не сдвигались между вставками.
void CodeEditorWidget::applyTextEdits(QPlainTextEdit *editor, const QVector<LSPTextEdit> &edits) const
{
    if (!editor)
        return;

    QTextCursor cursor(editor->document());
    cursor.beginEditBlock();

    QVector<LSPTextEdit> sortedEdits = edits;
    std::sort(sortedEdits.begin(), sortedEdits.end(),
              [](const LSPTextEdit &a, const LSPTextEdit &b) {
        if (a.range.start.line != b.range.start.line)
            return a.range.start.line > b.range.start.line;
        return a.range.start.character > b.range.start.character;
    });

    for (const auto &edit : sortedEdits) {
        QTextBlock startBlock = editor->document()->findBlockByNumber(edit.range.start.line);
        QTextBlock endBlock = editor->document()->findBlockByNumber(edit.range.end.line);
        if (!startBlock.isValid())
            continue;
        if (!endBlock.isValid())
            endBlock = startBlock;

        const int startPos = startBlock.position() + qMin(edit.range.start.character, startBlock.length() - 1);
        const int endPos = endBlock.position() + qMin(edit.range.end.character, endBlock.length() - 1);

        cursor.setPosition(startPos);
        cursor.setPosition(endPos, QTextCursor::KeepAnchor);
        cursor.insertText(edit.newText);
    }

    cursor.endEditBlock();
}

CodeEditorTab *CodeEditorWidget::findTabForFile(const QString &path) const
{
    for (int i = 0; i < m_tabWidget->count(); ++i) {
        auto *tab = qobject_cast<CodeEditorTab *>(m_tabWidget->widget(i));
        if (tab && tab->filePath() == path)
            return tab;
    }
    return nullptr;
}

void CodeEditorWidget::openCustomTab(QWidget *widget, const QString &title, const QString &path)
{
    // Если уже открыта — переключаемся
    auto *existing = findCustomTabWidget(path);
    if (existing) {
        m_tabWidget->setCurrentWidget(existing);
        return;
    }

    int index = m_tabWidget->addTab(widget, makeCustomTabTitle(widget, title));
    m_tabWidget->setTabToolTip(index, path);
    m_tabWidget->setCurrentIndex(index);
    m_customTabs[path] = widget;

    if (auto *moduleEditor = qobject_cast<ModuleEditorWidget *>(widget)) {
        connectModuleEditorSignals(moduleEditor);
        connect(moduleEditor, &ModuleEditorWidget::modificationChanged, this, [this, widget, title, path](bool) {
            const int currentIndex = m_tabWidget->indexOf(widget);
            if (currentIndex < 0)
                return;
            m_tabWidget->setTabText(currentIndex, makeCustomTabTitle(widget, title));
            m_tabWidget->setTabToolTip(currentIndex, path);
            emit currentTabChanged();
        });
        connect(moduleEditor, &ModuleEditorWidget::moduleSaved, this, [this, moduleEditor, widget, title, path](const QString &, const QString &) {
            const int currentIndex = m_tabWidget->indexOf(widget);
            if (currentIndex < 0)
                return;
            m_tabWidget->setTabText(currentIndex, makeCustomTabTitle(widget, title));
            m_tabWidget->setTabToolTip(currentIndex, path);
            if (m_lspClient && m_lspClient->isRunning()) {
                const QString documentPath = moduleEditor->lspDocumentPath();
                if (!documentPath.isEmpty())
                    m_lspClient->didSave(LSPClient::pathToUri(documentPath));
            }
            emit currentTabChanged();
        });
    }
}

// Ищет уже открытую custom-вкладку по её файловому пути.
QWidget *CodeEditorWidget::findCustomTabWidget(const QString &path) const
{
    auto it = m_customTabs.find(path);
    if (it != m_customTabs.end() && m_tabWidget->indexOf(it.value()) >= 0)
        return it.value();
    return nullptr;
}

// Возвращает текущую custom-вкладку, если активна не стандартная code-вкладка.
QWidget *CodeEditorWidget::currentCustomTabWidget() const
{
    QWidget *w = m_tabWidget->currentWidget();
    // Если это не CodeEditorTab, значит это кастомная вкладка
    if (w && !qobject_cast<CodeEditorTab *>(w))
        return w;
    return nullptr;
}

} // namespace DeltaQ
