// Дерево проекта — навигация по файлам
#include "ProjectTreeView.h"
#include <QFileInfo>
#include <QInputDialog>
#include <QMessageBox>
#include <QDesktopServices>
#include <QUrl>
#include <QFile>
#include <QDir>
#include <QDirIterator>
#include <QPainter>
#include <QRegularExpression>

namespace DeltaQ {

namespace {

struct BadgeSpec {
    QString text;
    QColor background;
    QColor foreground = Qt::white;
};

struct GeneratedOriginInfo {
    bool isGenerated = false;
    QString sourceKind;
    QString sourceName;
};

// Читает banner generated-файла и восстанавливает путь к его source-of-truth.
GeneratedOriginInfo inspectGeneratedFile(const QString &path)
{
    GeneratedOriginInfo info;

    QFile file(path);
    if (!file.open(QIODevice::ReadOnly | QIODevice::Text))
        return info;

    const QStringList lines = QString::fromUtf8(file.read(256)).split('\n');
    if (lines.isEmpty() || !lines.first().contains("Generated by DeltaQ IDE."))
        return info;

    info.isGenerated = true;
    static const QRegularExpression sourceRx(
        "^// Source: (graph|UI layout) '([^']+)'(?: \\(id: ([^)]+)\\))?$");

    for (const auto &line : lines.mid(1, 3)) {
        const auto match = sourceRx.match(line);
        if (match.hasMatch()) {
            info.sourceKind = match.captured(1);
            info.sourceName = match.captured(2);
            break;
        }
    }

    return info;
}

// Рисует компактный бейдж справа от имени файла в дереве проекта.
void drawBadge(QPainter *painter, const QRect &itemRect, int &x, const BadgeSpec &badge)
{
    const int badgeHeight = 14;
    const int textWidth = painter->fontMetrics().horizontalAdvance(badge.text) + 8;
    QRect badgeRect(x - textWidth, itemRect.top() + (itemRect.height() - badgeHeight) / 2,
                    textWidth, badgeHeight);
    painter->setBrush(badge.background);
    painter->setPen(Qt::NoPen);
    painter->drawRoundedRect(badgeRect, 3, 3);
    painter->setPen(badge.foreground);
    QFont font = painter->font();
    font.setPixelSize(10);
    font.setBold(true);
    painter->setFont(font);
    painter->drawText(badgeRect, Qt::AlignCenter, badge.text);
    x = badgeRect.left() - 4;
}

} // namespace

// --- DiagnosticDelegate ---

void DiagnosticDelegate::paint(QPainter *painter, const QStyleOptionViewItem &option,
                                const QModelIndex &index) const
{
    QStyledItemDelegate::paint(painter, option, index);

    // Получаем путь файла из модели
    auto *model = qobject_cast<const QFileSystemModel *>(index.model());
    if (!model) return;

    QString path = model->filePath(index);
    const auto it = m_diagnosticCounts.find(path);
    const int errors = (it == m_diagnosticCounts.end()) ? 0 : it.value().first;
    const int warnings = (it == m_diagnosticCounts.end()) ? 0 : it.value().second;
    const bool generated = m_generatedFiles.contains(path);
    if (!generated && errors == 0 && warnings == 0)
        return;

    painter->save();
    painter->setRenderHint(QPainter::Antialiasing);

    int x = option.rect.right() - 4;

    if (generated) {
        drawBadge(painter, option.rect, x, BadgeSpec{
            "gen",
            QColor(90, 90, 90)
        });
    }

    // Бейдж предупреждений (жёлтый) — рисуем первым (левее)
    if (warnings > 0) {
        drawBadge(painter, option.rect, x, BadgeSpec{
            QString::number(warnings),
            QColor(255, 180, 0)
        });
    }

    // Бейдж ошибок (красный)
    if (errors > 0) {
        drawBadge(painter, option.rect, x, BadgeSpec{
            QString::number(errors),
            QColor(220, 50, 50)
        });
    }

    painter->restore();
}

void DiagnosticDelegate::setDiagnosticCounts(const QString &path, int errors, int warnings)
{
    if (errors == 0 && warnings == 0)
        m_diagnosticCounts.remove(path);
    else
        m_diagnosticCounts[path] = {errors, warnings};
}

void DiagnosticDelegate::setGeneratedFile(const QString &path, bool generated)
{
    // Хранит generated-статус отдельно от диагностик, чтобы не смешивать эти категории.
    if (generated)
        m_generatedFiles.insert(path);
    else
        m_generatedFiles.remove(path);
}

void DiagnosticDelegate::clearGeneratedFiles()
{
    m_generatedFiles.clear();
}

bool DiagnosticDelegate::isGeneratedFile(const QString &path) const
{
    return m_generatedFiles.contains(path);
}

// --- ProjectTreeView ---

ProjectTreeView::ProjectTreeView(QWidget *parent)
    : QTreeView(parent)
    , m_model(new QFileSystemModel(this))
    , m_delegate(new DiagnosticDelegate(this))
{
    m_model->setNameFilters({"*.c", "*.cpp", "*.h", "*.hpp",
                              "*.dqmod", "*.dqgraph", "*.dqui", "*.dqproj",
                              "CMakeLists.txt"});
    m_model->setNameFilterDisables(false);
    setModel(m_model);
    setItemDelegate(m_delegate);

    // Скрываем лишние колонки (размер, тип, дата)
    for (int i = 1; i < m_model->columnCount(); ++i)
        hideColumn(i);

    setHeaderHidden(true);
    setAnimated(true);
    setSortingEnabled(true);
    setContextMenuPolicy(Qt::CustomContextMenu);

    connect(this, &QTreeView::doubleClicked, this, &ProjectTreeView::onDoubleClicked);
    connect(this, &QWidget::customContextMenuRequested, this, &ProjectTreeView::showContextMenu);
}

void ProjectTreeView::setRootPath(const QString &path)
{
    m_rootPath = path;
    auto idx = m_model->setRootPath(path);
    setRootIndex(idx);
    refreshGeneratedFiles();
}

void ProjectTreeView::updateDiagnosticCounts(const QString &path, int errors, int warnings)
{
    m_delegate->setDiagnosticCounts(path, errors, warnings);
    viewport()->update();
}

void ProjectTreeView::markGeneratedFile(const QString &path, bool generated)
{
    // Инкрементально обновляет generated-маркер после pre-build без полного пересканирования.
    m_delegate->setGeneratedFile(path, generated);
    viewport()->update();
}

bool ProjectTreeView::isGeneratedFile(const QString &path) const
{
    return m_delegate->isGeneratedFile(path);
}

QString ProjectTreeView::generatedOriginPath(const QString &path) const
{
    // Возвращает первоисточник generated-файла в проектной структуре.
    if (!isGeneratedFile(path) || m_rootPath.isEmpty())
        return {};

    const GeneratedOriginInfo info = inspectGeneratedFile(path);
    if (!info.isGenerated || info.sourceKind.isEmpty() || info.sourceName.isEmpty())
        return {};

    if (info.sourceKind == "graph")
        return QDir(m_rootPath).absoluteFilePath("graphs/" + info.sourceName + ".dqgraph");
    if (info.sourceKind == "UI layout")
        return QDir(m_rootPath).absoluteFilePath("ui/" + info.sourceName + ".dqui");
    return {};
}

void ProjectTreeView::refreshGeneratedFiles()
{
    // При открытии проекта заново находит generated-артефакты по их banner-ам.
    m_delegate->clearGeneratedFiles();
    if (m_rootPath.isEmpty()) {
        viewport()->update();
        return;
    }

    QDirIterator it(m_rootPath, {"*.c", "*.cpp", "*.h", "*.hpp"},
                    QDir::Files, QDirIterator::Subdirectories);
    while (it.hasNext()) {
        const QString path = it.next();
        if (inspectGeneratedFile(path).isGenerated)
            m_delegate->setGeneratedFile(path, true);
    }

    viewport()->update();
}

void ProjectTreeView::onDoubleClicked(const QModelIndex &index)
{
    QString path = m_model->filePath(index);
    QFileInfo fi(path);
    if (!fi.isFile())
        return;

    // По умолчанию generated-файл открывает свой source-of-truth, а не результат pre-build.
    const QString originPath = generatedOriginPath(path);
    emit fileSelected(originPath.isEmpty() ? path : originPath);
}

void ProjectTreeView::showContextMenu(const QPoint &pos)
{
    QModelIndex index = indexAt(pos);
    QString path = index.isValid() ? m_model->filePath(index) : m_rootPath;
    QFileInfo fi(path);

    QMenu menu(this);

    if (fi.isFile()) {
        const QString originPath = generatedOriginPath(path);
        if (!originPath.isEmpty()) {
            menu.addAction(tr("Open Source of Truth"), this, [this, originPath]() {
                emit fileSelected(originPath);
            });
            menu.addAction(tr("Open Generated File"), this, [this, path]() {
                emit fileSelected(path);
            });
        } else {
            menu.addAction(tr("Open"), this, [this, path]() {
                emit fileSelected(path);
            });
        }
        menu.addSeparator();
    }

    // Определяем директорию для создания файла
    QString dir = fi.isDir() ? path : fi.absolutePath();

    menu.addAction(tr("New File..."), this, [this, dir]() {
        emit newFileRequested(dir);
    });

    menu.addAction(tr("New Folder..."), this, [this, dir]() {
        QString name = QInputDialog::getText(this, tr("New Folder"), tr("Folder name:"));
        if (name.isEmpty()) return;
        QDir(dir).mkdir(name);
    });

    if (fi.isFile()) {
        menu.addSeparator();
        menu.addAction(tr("Delete"), this, [this, path, fi]() {
            auto result = QMessageBox::question(this, tr("Delete File"),
                tr("Delete '%1'?").arg(fi.fileName()),
                QMessageBox::Yes | QMessageBox::No);
            if (result == QMessageBox::Yes)
                QFile::remove(path);
        });
    }

    menu.addSeparator();
    menu.addAction(tr("Show in File Manager"), this, [dir]() {
        QDesktopServices::openUrl(QUrl::fromLocalFile(dir));
    });

    menu.exec(viewport()->mapToGlobal(pos));
}

} // namespace DeltaQ
