// Тесты SDL2CodeGenerator
#include <QTest>
#include "../../src/uiDesigner/SDL2CodeGenerator.h"
#include <deltaq/UILayout.h>

using namespace DeltaQ;

class TestSDL2CodeGenerator : public QObject {
    Q_OBJECT

private:
    UILayout createTestLayout()
    {
        UILayout layout = UILayout::create("TestApp");
        layout.window.geometry = QRectF(0, 0, 800, 600);

        UIWidget btn = UIWidget::create("Button", "btnOk");
        btn.geometry = QRectF(10, 10, 120, 40);
        btn.properties["text"] = "OK";
        btn.events["onClick"] = "on_ok_click";
        layout.window.children.append(btn);

        UIWidget lbl = UIWidget::create("Label", "lblTitle");
        lbl.geometry = QRectF(10, 60, 200, 30);
        lbl.properties["text"] = "Hello DeltaQ";
        layout.window.children.append(lbl);

        UIWidget tf = UIWidget::create("TextField", "tfName");
        tf.geometry = QRectF(10, 100, 200, 30);
        tf.properties["placeholder"] = "Enter name";
        layout.window.children.append(tf);

        return layout;
    }

private slots:
    void testGenerateProduces5Files()
    {
        UILayout layout = createTestLayout();
        GeneratedCode code = SDL2CodeGenerator::generate(layout);

        QVERIFY(!code.mainFile.isEmpty());
        QVERIFY(!code.uiHeader.isEmpty());
        QVERIFY(!code.uiSource.isEmpty());
        QVERIFY(!code.eventsHeader.isEmpty());
        QVERIFY(!code.eventsSource.isEmpty());
    }

    void testMainFileUsesBackendBoundary()
    {
        UILayout layout = createTestLayout();
        GeneratedCode code = SDL2CodeGenerator::generate(layout);

        QVERIFY(code.mainFile.contains("Generated by DeltaQ IDE."));
        QVERIFY(code.mainFile.contains("Source: UI layout 'TestApp'"));
        QVERIFY(code.mainFile.contains("UI contract layer: contract"));
        QVERIFY(code.mainFile.contains("UI backend: SDL2"));
        QVERIFY(code.mainFile.contains("File role: SDL2 main source (main.c)."));
        QVERIFY(code.mainFile.contains("DQ_UIBackendContext backend;"));
        QVERIFY(code.mainFile.contains("dq_ui_backend_init(&backend"));
        QVERIFY(code.mainFile.contains("dq_ui_backend_poll_event(&event)"));
        QVERIFY(code.mainFile.contains("DQ_UIRuntimeEvent runtime_event;"));
        QVERIFY(code.mainFile.contains("dq_ui_backend_translate_event(&event, &runtime_event)"));
        QVERIFY(code.mainFile.contains("dq_ui_backend_window_size(&backend, &window_width, &window_height);"));
        QVERIFY(code.mainFile.contains("ui_apply_layout(&ui, window_width, window_height);"));
        QVERIFY(code.mainFile.contains("dq_ui_backend_begin_frame(&backend)"));
        QVERIFY(code.mainFile.contains("dq_ui_backend_end_frame(&backend)"));
        QVERIFY(code.mainFile.contains("dq_ui_backend_shutdown(&backend)"));
        QVERIFY(code.mainFile.contains("ui_init"));
        QVERIFY(code.mainFile.contains("ui_render"));
        QVERIFY(code.mainFile.contains("ui_handle_event"));
        QVERIFY(!code.mainFile.contains("SDL_CreateWindow("));
    }

    void testUIHeaderContainsStructs()
    {
        UILayout layout = createTestLayout();
        GeneratedCode code = SDL2CodeGenerator::generate(layout);

        QVERIFY(code.uiHeader.contains("File role: UI header (ui.h)."));
        QVERIFY(code.uiHeader.contains("DQ_Button"));
        QVERIFY(code.uiHeader.contains("DQ_Label"));
        QVERIFY(code.uiHeader.contains("DQ_TextField"));
        QVERIFY(code.uiHeader.contains("UIState"));
        QVERIFY(code.uiHeader.contains("typedef struct {\n    DQ_UIBackendWindow *window;"));
        QVERIFY(code.uiHeader.contains("bool dq_ui_backend_init"));
        QVERIFY(code.uiHeader.contains("typedef SDL_Renderer DQ_UIBackendRenderer;"));
        QVERIFY(code.uiHeader.contains("typedef enum {\n    DQ_UIRuntimeEvent_None = 0,"));
        QVERIFY(code.uiHeader.contains("typedef enum {\n    DQ_UIWidget_None = 0,"));
        QVERIFY(code.uiHeader.contains("typedef enum {\n    DQ_UIRuntimeLayout_None = 0,"));
        QVERIFY(code.uiHeader.contains("typedef struct {\n    int mouse_x;\n    int mouse_y;\n    int window_width;\n    int window_height;\n    DQ_UIWidgetId hovered_widget;"));
        QVERIFY(code.uiHeader.contains("typedef struct {\n    DQ_UIRuntimeLayoutKind kind;\n    int margin;\n    int spacing;\n} DQ_UIRuntimeLayoutSpec;"));
        QVERIFY(code.uiHeader.contains("typedef struct {\n    bool left;\n    bool right;\n    bool top;\n    bool bottom;"));
        QVERIFY(code.uiHeader.contains("DQ_UIRuntimeContext runtime;"));
        QVERIFY(code.uiHeader.contains("void dq_ui_backend_window_size(DQ_UIBackendContext *backend, int *width, int *height);"));
        QVERIFY(code.uiHeader.contains("bool dq_ui_backend_translate_event"));
        QVERIFY(code.uiHeader.contains("void ui_apply_layout(UIState *ui, int window_width, int window_height);"));
        QVERIFY(code.uiHeader.contains("void ui_handle_event(UIState *ui, const DQ_UIRuntimeEvent *event);"));
        QVERIFY(code.uiHeader.contains("void ui_init"));
    }

    void testUISourceContainsInit()
    {
        UILayout layout = createTestLayout();
        GeneratedCode code = SDL2CodeGenerator::generate(layout);

        QVERIFY(code.uiSource.contains("ui_init"));
        QVERIFY(code.uiSource.contains("ui_render"));
        QVERIFY(code.uiSource.contains("ui_handle_event"));
        QVERIFY(code.uiSource.contains("bool dq_ui_backend_init(DQ_UIBackendContext *backend"));
        QVERIFY(code.uiSource.contains("void dq_ui_backend_begin_frame(DQ_UIBackendContext *backend)"));
        QVERIFY(code.uiSource.contains("bool dq_ui_backend_translate_event(const DQ_UIBackendEvent *backend_event,"));
        QVERIFY(code.uiSource.contains("void dq_ui_backend_window_size(DQ_UIBackendContext *backend, int *width, int *height)"));
        QVERIFY(code.uiSource.contains("static DQ_UIWidgetId dq_ui_runtime_hit_test(const UIState *ui, int x, int y)"));
        QVERIFY(code.uiSource.contains("static void dq_ui_runtime_sync_state(UIState *ui)"));
        QVERIFY(code.uiSource.contains("static void dq_ui_runtime_dispatch_click(UIState *ui, DQ_UIWidgetId widget_id)"));
        QVERIFY(code.uiSource.contains("static SDL_Rect dq_ui_runtime_rect_from_base(const SDL_Rect *parent_rect,"));
        QVERIFY(code.uiSource.contains("static void dq_ui_runtime_apply_anchor_spec(SDL_Rect *rect,"));
        QVERIFY(code.uiSource.contains("static void dq_ui_runtime_apply_hbox(const SDL_Rect *parent_rect,"));
        QVERIFY(code.uiSource.contains("static void dq_ui_runtime_apply_layout_spec(const SDL_Rect *parent_rect,"));
        QVERIFY(code.uiSource.contains("static const DQ_UIRuntimeLayoutSpec dq_ui_layoutspec_root = {"));
        QVERIFY(code.uiSource.contains("static const DQ_UIRuntimeAnchorSpec dq_ui_anchorspec_btnOk = {"));
        QVERIFY(code.uiSource.contains("void ui_apply_layout(UIState *ui, int window_width, int window_height)"));
        QVERIFY(code.uiSource.contains("ui->runtime.hovered_widget = dq_ui_runtime_hit_test(ui, event->mouse_x, event->mouse_y);"));
        QVERIFY(code.uiSource.contains("case DQ_UIRuntimeEvent_TextInput:"));
        QVERIFY(code.uiSource.contains("dq_ui_runtime_append_text(ui, ui->runtime.focused_widget, event->text);"));
        QVERIFY(code.uiSource.contains("dq_ui_runtime_sync_state(ui);"));
        QVERIFY(code.uiSource.contains("case DQ_UIRuntimeEvent_MouseDown:"));
        QVERIFY(code.uiSource.contains("btnOk"));
        QVERIFY(code.uiSource.contains("lblTitle"));
        QVERIFY(code.uiSource.contains("tfName"));
    }

    void testContractMetadataDrivesWidgetGeneration()
    {
        UILayout layout = UILayout::create("ContractDriven");

        UIWidget tf = UIWidget::create("TextField", "tfContract");
        tf.type = "LegacyTextField";
        tf.properties["placeholder"] = "Contract placeholder";
        layout.window.children.append(tf);

        GeneratedCode code = SDL2CodeGenerator::generate(layout);

        QVERIFY(code.uiHeader.contains("DQ_LegacyTextField"));
        QVERIFY(code.uiSource.contains("ui->tfContract.placeholder = \"Contract placeholder\";"));
        QVERIFY(code.uiSource.contains("ui->tfContract.focused = ui->runtime.focused_widget == DQ_UIWidget_tfContract;"));
    }

    void testEventsHeaderContainsHandlers()
    {
        UILayout layout = createTestLayout();
        GeneratedCode code = SDL2CodeGenerator::generate(layout);

        QVERIFY(code.eventsHeader.contains("on_ok_click"));
    }

    void testEventsSourceContainsHandlers()
    {
        UILayout layout = createTestLayout();
        GeneratedCode code = SDL2CodeGenerator::generate(layout);

        QVERIFY(code.eventsSource.contains("File role: event implementation (ui_events.c)."));
        QVERIFY(code.eventsSource.contains("on_ok_click"));
        QVERIFY(code.eventsSource.contains("TODO"));
    }
};

QTEST_APPLESS_MAIN(TestSDL2CodeGenerator)
#include "test_SDL2CodeGenerator.moc"
