#include <QDir>
#include <QFile>
#include <QFileInfo>
#include <QMetaObject>
#include <QTemporaryDir>
#include <QTextBlock>
#include <QTextEdit>
#include <QTextFragment>
#include <QTreeWidget>
#include <QTest>

#include <deltaq/UILayout.h>

#include "../../src/core/MainWindow.h"
#include "../../src/core/ProjectManager.h"
#include "../../src/core/UILayoutStore.h"
#include "../../src/editor/CodeEditorWidget.h"
#include "../../src/editor/CodeEditorTab.h"
#include "../../src/editor/ProjectTreeView.h"

using namespace DeltaQ;

Q_DECLARE_METATYPE(QTreeWidgetItem *)

namespace {

enum BuildDiagnosticTestRole {
    ResolvedPathRole = Qt::UserRole + 1,
    OriginPathRole,
    LineRole,
    ColumnRole
};

} // namespace

class TestMainWindowBuildOutputNavigation : public QObject {
    Q_OBJECT

private:
    static QString writeFile(const QString &path, const QString &content)
    {
        QDir().mkpath(QFileInfo(path).absolutePath());

        QFile file(path);
        if (!file.open(QIODevice::WriteOnly | QIODevice::Text))
            return {};
        file.write(content.toUtf8());
        file.close();
        return path;
    }

    static void processUi()
    {
        QCoreApplication::processEvents();
        QCoreApplication::sendPostedEvents(nullptr, QEvent::DeferredDelete);
        QCoreApplication::processEvents();
    }

    static QTextCharFormat firstFragmentFormat(const QTextBlock &block)
    {
        for (auto it = block.begin(); !it.atEnd(); ++it) {
            const QTextFragment fragment = it.fragment();
            if (fragment.isValid() && !fragment.text().isEmpty())
                return fragment.charFormat();
        }
        return {};
    }

private slots:
    void initTestCase()
    {
        qRegisterMetaType<QTreeWidgetItem *>("QTreeWidgetItem*");
    }

    void regularBuildErrorOpensFileAtLocation()
    {
        QTemporaryDir tmpDir;
        QVERIFY(tmpDir.isValid());

        MainWindow window;
        auto *editor = window.findChild<CodeEditorWidget *>();
        QVERIFY(editor != nullptr);

        const QString filePath = writeFile(
            tmpDir.path() + "/manual.c",
            "int a = 0;\n"
            "int broken = 1;\n"
            "return 0;\n");
        QVERIFY(!filePath.isEmpty());

        QVERIFY(QMetaObject::invokeMethod(
            &window,
            "navigateBuildOutputLine",
            Q_ARG(QString, QString("%1:2:5: error: test failure").arg(filePath))));
        processUi();

        auto *tab = editor->currentTab();
        QVERIFY(tab != nullptr);
        QCOMPARE(tab->filePath(), filePath);
        QCOMPARE(tab->editor()->textCursor().blockNumber() + 1, 2);
        QCOMPARE(tab->editor()->textCursor().columnNumber() + 1, 5);
    }

    void generatedBuildErrorOpensLayoutOrigin()
    {
        QTemporaryDir tmpDir;
        QVERIFY(tmpDir.isValid());

        MainWindow window;
        auto *editor = window.findChild<CodeEditorWidget *>();
        auto *projectTree = window.findChild<ProjectTreeView *>();
        auto *uiLayoutStore = window.findChild<UILayoutStore *>();
        QVERIFY(editor != nullptr);
        QVERIFY(projectTree != nullptr);
        QVERIFY(uiLayoutStore != nullptr);

        const QString projectDir = tmpDir.path() + "/proj";
        QVERIFY(window.projectManager()->createProject("NavProj", projectDir));

        const UILayout layout = UILayout::create("main");
        uiLayoutStore->registerLayout(layout);
        QVERIFY(uiLayoutStore->saveAll(projectDir));

        const QString generatedPath = writeFile(
            projectDir + "/src/ui/main.c",
            QString("// Generated by DeltaQ IDE.\n"
                    "// Source: UI layout 'main' (id: %1)\n"
                    "// File role: UI implementation (main.c).\n"
                    "// Warning: this file is generated and may be overwritten.\n\n"
                    "int main(void) { return 0; }\n")
                .arg(layout.id));
        QVERIFY(!generatedPath.isEmpty());

        projectTree->setRootPath(projectDir);
        QVERIFY(projectTree->isGeneratedFile(generatedPath));

        QVERIFY(QMetaObject::invokeMethod(
            &window,
            "navigateBuildOutputLine",
            Q_ARG(QString, QString("../src/ui/main.c:12:4: error: generated failure"))));
        processUi();

        const QString layoutPath = projectDir + "/ui/main.dqui";
        auto *tab = editor->currentTab();
        QVERIFY(tab != nullptr);
        QCOMPARE(tab->filePath(), layoutPath);
        QCOMPARE(editor->currentCustomTabWidget(), nullptr);

        editor->closeAllTabs();
        projectTree->setRootPath(QString());
        QVERIFY(window.projectManager()->closeProject());
        processUi();
    }

    void navigableBuildOutputLinesAreHighlighted()
    {
        MainWindow window;
        auto *buildOutput = window.findChild<QTextEdit *>("buildOutputView");
        QVERIFY(buildOutput != nullptr);

        QVERIFY(QMetaObject::invokeMethod(
            &window,
            "appendBuildOutputChunk",
            Q_ARG(QString, QString("ordinary build log line\n"))));
        QVERIFY(QMetaObject::invokeMethod(
            &window,
            "appendBuildOutputChunk",
            Q_ARG(QString, QString("../src/main.c:12:4: error: generated failure\n"))));
        processUi();

        QTextBlock firstBlock = buildOutput->document()->firstBlock();
        QVERIFY(firstBlock.isValid());
        QTextBlock secondBlock = firstBlock.next();
        QVERIFY(secondBlock.isValid());

        const QTextCharFormat plainFormat = firstFragmentFormat(firstBlock);
        const QTextCharFormat navigableFormat = firstFragmentFormat(secondBlock);
        QCOMPARE(plainFormat.underlineStyle(), QTextCharFormat::NoUnderline);
        QCOMPARE(navigableFormat.underlineStyle(), QTextCharFormat::SingleUnderline);
        QCOMPARE(navigableFormat.foreground().color(), QColor(0, 102, 204));
    }

    void buildDiagnosticsKeepOriginMetadataAndOpenOrigin()
    {
        QTemporaryDir tmpDir;
        QVERIFY(tmpDir.isValid());

        MainWindow window;

        auto *editor = window.findChild<CodeEditorWidget *>();
        auto *diagnostics = window.findChild<QTreeWidget *>("buildDiagnosticsView");
        auto *projectTree = window.findChild<ProjectTreeView *>();
        auto *uiLayoutStore = window.findChild<UILayoutStore *>();
        QVERIFY(editor != nullptr);
        QVERIFY(diagnostics != nullptr);
        QVERIFY(projectTree != nullptr);
        QVERIFY(uiLayoutStore != nullptr);

        const QString projectDir = tmpDir.path() + "/proj";
        QVERIFY(window.projectManager()->createProject("DiagProj", projectDir));

        const UILayout layout = UILayout::create("main");
        uiLayoutStore->registerLayout(layout);
        QVERIFY(uiLayoutStore->saveAll(projectDir));

        const QString generatedPath = writeFile(
            projectDir + "/src/ui/main.c",
            QString("// Generated by DeltaQ IDE.\n"
                    "// Source: UI layout 'main' (id: %1)\n"
                    "// File role: UI implementation (main.c).\n"
                    "// Warning: this file is generated and may be overwritten.\n\n"
                    "int main(void) { return 0; }\n")
                .arg(layout.id));
        QVERIFY(!generatedPath.isEmpty());

        projectTree->setRootPath(projectDir);
        QVERIFY(projectTree->isGeneratedFile(generatedPath));

        QVERIFY(QMetaObject::invokeMethod(
            &window,
            "addBuildDiagnosticEntry",
            Q_ARG(QString, QString("../src/ui/main.c")),
            Q_ARG(int, 12),
            Q_ARG(int, 4),
            Q_ARG(QString, QString("error")),
            Q_ARG(QString, QString("generated failure"))));
        processUi();

        QCOMPARE(diagnostics->topLevelItemCount(), 1);
        auto *item = diagnostics->topLevelItem(0);
        QVERIFY(item != nullptr);
        QCOMPARE(item->text(0), QString("error"));
        QCOMPARE(item->text(1), QString("main.c:12:4"));
        QCOMPARE(item->text(2), QString("main.dqui"));
        QCOMPARE(item->text(3), QString("generated failure"));
        QCOMPARE(item->data(0, ResolvedPathRole).toString(), generatedPath);
        QCOMPARE(item->data(0, OriginPathRole).toString(), projectDir + "/ui/main.dqui");
        QCOMPARE(item->data(0, LineRole).toInt(), 12);
        QCOMPARE(item->data(0, ColumnRole).toInt(), 4);

        QVERIFY(QMetaObject::invokeMethod(
            &window,
            "onBuildDiagnosticActivated",
            Qt::DirectConnection,
            Q_ARG(QTreeWidgetItem *, item),
            Q_ARG(int, 0)));
        processUi();

        auto *tab = editor->currentTab();
        QVERIFY(tab != nullptr);
        QCOMPARE(tab->filePath(), projectDir + "/ui/main.dqui");
        QCOMPARE(editor->currentCustomTabWidget(), nullptr);

        editor->closeAllTabs();
        projectTree->setRootPath(QString());
        QVERIFY(window.projectManager()->closeProject());
        processUi();
    }
};

QTEST_MAIN(TestMainWindowBuildOutputNavigation)
#include "test_MainWindowBuildOutputNavigation.moc"
