#include <QAction>
#include <QApplication>
#include <QFile>
#include <QStatusBar>
#include <QTemporaryDir>
#include <QTest>
#include <QToolBar>

#include "../../src/blockEditor/BlockEditorWidget.h"
#include "../../src/core/ActionManager.h"
#include "../../src/core/MainWindow.h"
#include "../../src/editor/CodeEditorWidget.h"

using namespace DeltaQ;

class TestMainWindowEditorActions : public QObject {
    Q_OBJECT

private:
    static QString writeFile(const QString &dirPath, const QString &fileName, const QString &content)
    {
        const QString path = dirPath + "/" + fileName;
        QFile file(path);
        if (!file.open(QIODevice::WriteOnly | QIODevice::Text))
            return {};
        file.write(content.toUtf8());
        file.close();
        return path;
    }

    static void processUi()
    {
        QCoreApplication::processEvents();
        QCoreApplication::sendPostedEvents(nullptr, QEvent::DeferredDelete);
        QCoreApplication::processEvents();
    }

private slots:
    void regularTextFilesEnableEditingActions()
    {
        MainWindow window;
        auto *editor = window.findChild<CodeEditorWidget *>();
        QVERIFY(editor != nullptr);

        QTemporaryDir tmpDir;
        QVERIFY(tmpDir.isValid());
        const QString path = writeFile(tmpDir.path(), "manual.c", "int main(void) { return 0; }\n");
        QVERIFY(!path.isEmpty());

        editor->openFile(path);
        processUi();

        QVERIFY(window.actionManager()->saveAction()->isEnabled());
        QVERIFY(window.actionManager()->action("edit.rename")->isEnabled());
        QVERIFY(window.actionManager()->action("edit.format")->isEnabled());
        QVERIFY(!window.actionManager()->action("edit.openGeneratedOrigin")->isEnabled());
    }

    void generatedTextFilesDisableEditingActions()
    {
        MainWindow window;
        auto *editor = window.findChild<CodeEditorWidget *>();
        QVERIFY(editor != nullptr);

        QTemporaryDir tmpDir;
        QVERIFY(tmpDir.isValid());
        const QString path = writeFile(
            tmpDir.path(),
            "main.c",
            "// Generated by DeltaQ IDE.\n"
            "// Source: graph 'main'\n"
            "// File role: generated C source from a DeltaQ graph.\n"
            "// Warning: this file is generated and may be overwritten.\n\n"
            "int main(void) { return 0; }\n");
        QVERIFY(!path.isEmpty());

        editor->openFile(path);
        processUi();

        QVERIFY(!window.actionManager()->saveAction()->isEnabled());
        QVERIFY(!window.actionManager()->action("edit.rename")->isEnabled());
        QVERIFY(!window.actionManager()->action("edit.format")->isEnabled());
        QVERIFY(window.actionManager()->action("edit.openGeneratedOrigin")->isEnabled());
    }

    void graphTabsStaySavableButNotTextEditable()
    {
        MainWindow window;
        auto *editor = window.findChild<CodeEditorWidget *>();
        QVERIFY(editor != nullptr);

        auto *graphEditor = new BlockEditorWidget(window.moduleRegistry(), window.commandBus());
        editor->openCustomTab(graphEditor, "demo.dqgraph", "/tmp/demo.dqgraph");
        processUi();

        QVERIFY(window.actionManager()->saveAction()->isEnabled());
        QVERIFY(!window.actionManager()->action("edit.rename")->isEnabled());
        QVERIFY(!window.actionManager()->action("edit.format")->isEnabled());
        QVERIFY(!window.actionManager()->action("edit.openGeneratedOrigin")->isEnabled());
    }

    void linuxExportActionIsRegisteredAndWired()
    {
        MainWindow window;
        QAction *exportAction = window.actionManager()->action("build.exportLinuxBundle");
        QVERIFY(exportAction != nullptr);
        QCOMPARE(exportAction->text(), "Export Linux Bundle");

        exportAction->trigger();
        processUi();

        QCOMPARE(window.statusBar()->currentMessage(), "No project open");
    }

    void projectActionsAreRegisteredAndWired()
    {
        MainWindow window;

        QAction *propertiesAction = window.actionManager()->action("project.properties");
        QAction *rescanAction = window.actionManager()->action("project.rescanToolchains");
        QAction *openBuildDirAction = window.actionManager()->action("project.openBuildDirectory");
        QAction *openDistDirAction = window.actionManager()->action("project.openDistDirectory");
        QVERIFY(propertiesAction != nullptr);
        QVERIFY(rescanAction != nullptr);
        QVERIFY(openBuildDirAction != nullptr);
        QVERIFY(openDistDirAction != nullptr);
        QCOMPARE(propertiesAction->text(), "Project Properties...");
        QCOMPARE(rescanAction->text(), "Rescan Toolchains");
        QCOMPARE(openBuildDirAction->text(), "Open Build Directory");
        QCOMPARE(openDistDirAction->text(), "Open Dist Directory");

        propertiesAction->trigger();
        processUi();
        QCOMPARE(window.statusBar()->currentMessage(), "No project open");

        rescanAction->trigger();
        processUi();
        QVERIFY(window.statusBar()->currentMessage().startsWith("Toolchain scan completed: "));

        openBuildDirAction->trigger();
        processUi();
        QCOMPARE(window.statusBar()->currentMessage(), "No project open");

        openDistDirAction->trigger();
        processUi();
        QCOMPARE(window.statusBar()->currentMessage(), "No project open");
    }

    void toolbarUsesIconsAndHoverDescriptions()
    {
        MainWindow window;

        auto *toolBar = window.findChild<QToolBar *>("mainToolBar");
        QVERIFY(toolBar != nullptr);
        QCOMPARE(toolBar->toolButtonStyle(), Qt::ToolButtonIconOnly);

        QAction *propertiesAction = window.actionManager()->action("project.properties");
        QAction *buildAction = window.actionManager()->action("build.build");
        QVERIFY(propertiesAction != nullptr);
        QVERIFY(buildAction != nullptr);
        QVERIFY(!propertiesAction->icon().isNull());
        QVERIFY(!propertiesAction->toolTip().isEmpty());
        QVERIFY(!propertiesAction->statusTip().isEmpty());
        QVERIFY(!buildAction->icon().isNull());
        QVERIFY(!buildAction->toolTip().isEmpty());
        QVERIFY(!buildAction->statusTip().isEmpty());
    }
};

QTEST_MAIN(TestMainWindowEditorActions)
#include "test_MainWindowEditorActions.moc"
