// Генератор SDL2 C-кода — реализация
#include "SDL2CodeGenerator.h"
#include <deltaq/UILayout.h>
#include <QTextStream>
#include <QVector>

namespace DeltaQ {

namespace {

// Добавляет в generated UI-файлы banner с layout-источником и ролью файла.
QString makeGeneratedLayoutBanner(const UILayout &layout, const QString &fileRole,
                                  const QString &fileName)
{
    QString banner;
    QTextStream out(&banner);
    out << "// Generated by DeltaQ IDE.\n";
    out << "// Source: UI layout '" << layout.name << "'";
    if (!layout.id.isEmpty())
        out << " (id: " << layout.id << ")";
    out << "\n";
    out << "// UI contract layer: "
        << layout.metadata.value("deltaq.ui.layer").toString("contract") << "\n";
    out << "// UI backend: SDL2\n";
    out << "// File role: " << fileRole << " (" << fileName << ").\n";
    out << "// Warning: this file is generated and may be overwritten.\n\n";
    return banner;
}

// Возвращает канонический UI contract type для generated runtime/codegen.
QString widgetContractType(const UIWidget &widget)
{
    const QString contractType = widget.contractType();
    return contractType.isEmpty() ? canonicalUIContractType(widget.type) : contractType;
}

// Сравнение по contract type, чтобы generated UI не зависел от legacy-имён `.dqui`.
bool widgetMatchesContract(const UIWidget &widget, const QString &contractType)
{
    return widgetContractType(widget) == contractType;
}

} // namespace

GeneratedCode SDL2CodeGenerator::generate(const UILayout &layout, const QString &baseName)
{
    GeneratedCode code;
    code.baseName     = baseName;
    code.mainFile     = generateMainFile(layout, baseName);
    code.uiHeader     = generateUIHeader(layout, baseName);
    code.uiSource     = generateUISource(layout, baseName);
    code.eventsHeader = generateEventsHeader(layout, baseName);
    code.eventsSource = generateEventsSource(layout, baseName);
    return code;
}

// --- Вспомогательные ---

QString SDL2CodeGenerator::sanitizeName(const QString &name)
{
    QString result;
    for (QChar c : name) {
        if (c.isLetterOrNumber() || c == '_')
            result += c;
        else
            result += '_';
    }
    if (!result.isEmpty() && result[0].isDigit())
        result.prepend('_');
    return result;
}

QString SDL2CodeGenerator::widgetStructName(const QString &type)
{
    return "DQ_" + type;
}

QString SDL2CodeGenerator::widgetRenderFunc(const QString &type)
{
    return "render_" + type.toLower();
}

void SDL2CodeGenerator::collectWidgets(const UIWidget &widget, QVector<const UIWidget *> &out)
{
    if (!widgetMatchesContract(widget, "window"))
        out.append(&widget);
    for (const auto &child : widget.children)
        collectWidgets(child, out);
}

void SDL2CodeGenerator::collectEvents(const UIWidget &widget, QMap<QString, QString> &out)
{
    for (auto it = widget.events.begin(); it != widget.events.end(); ++it)
        out[it.value()] = it.key(); // handler → event
    for (const auto &child : widget.children)
        collectEvents(child, out);
}

// --- main.c ---

QString SDL2CodeGenerator::generateMainFile(const UILayout &layout, const QString &baseName)
{
    QString s;
    QTextStream out(&s);

    out << makeGeneratedLayoutBanner(layout, "SDL2 main source", "main.c");
    out << "#include <stdbool.h>\n";
    out << "#include \"" << baseName << ".h\"\n";
    out << "#include \"" << baseName << "_events.h\"\n\n";

    out << "int main(int argc, char *argv[]) {\n";
    out << "    (void)argc; (void)argv;\n\n";

    int w = static_cast<int>(layout.window.geometry.width());
    int h = static_cast<int>(layout.window.geometry.height());

    out << "    DQ_UIBackendContext backend;\n";
    out << "    if (!dq_ui_backend_init(&backend, \"" << layout.name << "\", " << w << ", " << h << ")) {\n";
    out << "        return 1;\n";
    out << "    }\n\n";

    out << "    UIState ui;\n";
    out << "    ui_init(&ui);\n\n";
    out << "    int window_width = 0;\n";
    out << "    int window_height = 0;\n";
    out << "    dq_ui_backend_window_size(&backend, &window_width, &window_height);\n";
    out << "    ui_apply_layout(&ui, window_width, window_height);\n\n";

    out << "    bool running = true;\n";
    out << "    DQ_UIBackendEvent event;\n";
    out << "    DQ_UIRuntimeEvent runtime_event;\n";
    out << "    Uint32 last_tick = dq_ui_backend_ticks();\n\n";

    out << "    while (running) {\n";
    out << "        while (dq_ui_backend_poll_event(&event)) {\n";
    out << "            if (!dq_ui_backend_translate_event(&event, &runtime_event)) {\n";
    out << "                continue;\n";
    out << "            }\n";
    out << "            if (runtime_event.kind == DQ_UIRuntimeEvent_Quit) {\n";
    out << "                running = false;\n";
    out << "                break;\n";
    out << "            }\n";
    out << "            ui_handle_event(&ui, &runtime_event);\n";
    out << "        }\n\n";
    out << "        Uint32 now = dq_ui_backend_ticks();\n";
    out << "        ui_update(&ui, now - last_tick);\n";
    out << "        last_tick = now;\n\n";
    out << "        dq_ui_backend_window_size(&backend, &window_width, &window_height);\n";
    out << "        ui_apply_layout(&ui, window_width, window_height);\n";
    out << "        dq_ui_backend_begin_frame(&backend);\n";
    out << "        ui_render(&ui, backend.renderer);\n";
    out << "        dq_ui_backend_end_frame(&backend);\n";
    out << "    }\n\n";

    out << "    if (ui.font) TTF_CloseFont(ui.font);\n";
    out << "    dq_ui_backend_shutdown(&backend);\n";
    out << "    return 0;\n";
    out << "}\n";

    return s;
}

// --- ui.h ---

QString SDL2CodeGenerator::generateUIHeader(const UILayout &layout, const QString &baseName)
{
    QVector<const UIWidget *> widgets;
    collectWidgets(layout.window, widgets);

    QString s;
    QTextStream out(&s);

    out << makeGeneratedLayoutBanner(layout, "UI header", baseName + ".h");
    out << "#pragma once\n\n";
    out << "#include <SDL2/SDL.h>\n";
    out << "#include <SDL2/SDL_ttf.h>\n";
    out << "#include <stdbool.h>\n\n";

    // Явная backend boundary: SDL2 остаётся реализацией backend v1,
    // а остальной generated UI-код работает через DQ_UIBackend* API.
    out << "typedef SDL_Window DQ_UIBackendWindow;\n";
    out << "typedef SDL_Renderer DQ_UIBackendRenderer;\n";
    out << "typedef SDL_Event DQ_UIBackendEvent;\n";
    out << "typedef TTF_Font DQ_UIBackendFont;\n\n";

    out << "typedef struct {\n";
    out << "    DQ_UIBackendWindow *window;\n";
    out << "    DQ_UIBackendRenderer *renderer;\n";
    out << "} DQ_UIBackendContext;\n\n";

    out << "bool dq_ui_backend_init(DQ_UIBackendContext *backend, const char *title, int width, int height);\n";
    out << "void dq_ui_backend_shutdown(DQ_UIBackendContext *backend);\n";
    out << "bool dq_ui_backend_poll_event(DQ_UIBackendEvent *event);\n";
    out << "Uint32 dq_ui_backend_ticks(void);\n";
    out << "DQ_UIBackendWindow *dq_ui_backend_window(DQ_UIBackendContext *backend);\n";
    out << "DQ_UIBackendRenderer *dq_ui_backend_renderer(DQ_UIBackendContext *backend);\n";
    out << "void dq_ui_backend_window_size(DQ_UIBackendContext *backend, int *width, int *height);\n";
    out << "void dq_ui_backend_release_renderer(DQ_UIBackendContext *backend);\n";
    out << "void dq_ui_backend_release_window(DQ_UIBackendContext *backend);\n";
    out << "void dq_ui_backend_begin_frame(DQ_UIBackendContext *backend);\n";
    out << "void dq_ui_backend_end_frame(DQ_UIBackendContext *backend);\n";
    out << "\n";

    // Нормализованная модель события UI runtime позволяет убрать прямую
    // зависимость ui_handle_event от SDL_Event и других backend API.
    out << "typedef enum {\n";
    out << "    DQ_UIRuntimeEvent_None = 0,\n";
    out << "    DQ_UIRuntimeEvent_Quit,\n";
    out << "    DQ_UIRuntimeEvent_MouseMove,\n";
    out << "    DQ_UIRuntimeEvent_MouseDown,\n";
    out << "    DQ_UIRuntimeEvent_MouseUp,\n";
    out << "    DQ_UIRuntimeEvent_MouseWheel,\n";
    out << "    DQ_UIRuntimeEvent_TextInput,\n";
    out << "    DQ_UIRuntimeEvent_KeyBackspace\n";
    out << "} DQ_UIRuntimeEventKind;\n\n";

    out << "typedef struct {\n";
    out << "    DQ_UIRuntimeEventKind kind;\n";
    out << "    int mouse_x;\n";
    out << "    int mouse_y;\n";
    out << "    int wheel_delta_y;\n";
    out << "    char text[32];\n";
    out << "} DQ_UIRuntimeEvent;\n\n";

    out << "bool dq_ui_backend_translate_event(const DQ_UIBackendEvent *backend_event,\n";
    out << "                                   DQ_UIRuntimeEvent *runtime_event);\n\n";

    // Явная внутренняя runtime-модель отделяет маршрутизацию событий
    // и состояния UI от backend-специфики SDL2.
    out << "typedef enum {\n";
    out << "    DQ_UIWidget_None = 0,\n";
    for (const auto *w : widgets) {
        out << "    DQ_UIWidget_" << sanitizeName(w->name) << ",\n";
    }
    out << "} DQ_UIWidgetId;\n\n";

    out << "typedef struct {\n";
    out << "    int mouse_x;\n";
    out << "    int mouse_y;\n";
    out << "    int window_width;\n";
    out << "    int window_height;\n";
    out << "    DQ_UIWidgetId hovered_widget;\n";
    out << "    DQ_UIWidgetId focused_widget;\n";
    out << "    DQ_UIWidgetId active_widget;\n";
    out << "} DQ_UIRuntimeContext;\n\n";

    // Runtime layout-спецификация делает размещение и anchors частью
    // явной внутренней модели UI, а не набором разрозненных literal-ов.
    out << "typedef enum {\n";
    out << "    DQ_UIRuntimeLayout_None = 0,\n";
    out << "    DQ_UIRuntimeLayout_HBox,\n";
    out << "    DQ_UIRuntimeLayout_VBox,\n";
    out << "    DQ_UIRuntimeLayout_Grid,\n";
    out << "    DQ_UIRuntimeLayout_Flow\n";
    out << "} DQ_UIRuntimeLayoutKind;\n\n";

    out << "typedef struct {\n";
    out << "    DQ_UIRuntimeLayoutKind kind;\n";
    out << "    int margin;\n";
    out << "    int spacing;\n";
    out << "} DQ_UIRuntimeLayoutSpec;\n\n";

    out << "typedef struct {\n";
    out << "    bool left;\n";
    out << "    bool right;\n";
    out << "    bool top;\n";
    out << "    bool bottom;\n";
    out << "    bool hcenter;\n";
    out << "    bool vcenter;\n";
    out << "    int left_margin;\n";
    out << "    int right_margin;\n";
    out << "    int top_margin;\n";
    out << "    int bottom_margin;\n";
    out << "} DQ_UIRuntimeAnchorSpec;\n\n";

    // Структуры для каждого типа (дедупликация)
    QSet<QString> emittedTypes;
    for (const auto *w : widgets) {
        const QString contractType = widgetContractType(*w);
        if (emittedTypes.contains(contractType)) continue;
        emittedTypes.insert(contractType);

        QString sn = widgetStructName(w->type);

        if (contractType == "button") {
            out << "typedef struct {\n";
            out << "    SDL_Rect rect;\n";
            out << "    SDL_Rect base_rect;\n";
            out << "    const char *text;\n";
            out << "    bool hovered;\n";
            out << "    bool pressed;\n";
            out << "} " << sn << ";\n\n";
        } else if (contractType == "label") {
            out << "typedef struct {\n";
            out << "    SDL_Rect rect;\n";
            out << "    SDL_Rect base_rect;\n";
            out << "    char text[64];\n";
            out << "} " << sn << ";\n\n";
        } else if (contractType == "text_field") {
            out << "typedef struct {\n";
            out << "    SDL_Rect rect;\n";
            out << "    SDL_Rect base_rect;\n";
            out << "    char text[256];\n";
            out << "    int cursor_pos;\n";
            out << "    bool focused;\n";
            out << "    const char *placeholder;\n";
            out << "} " << sn << ";\n\n";
        } else if (contractType == "text_area") {
            out << "typedef struct {\n";
            out << "    SDL_Rect rect;\n";
            out << "    SDL_Rect base_rect;\n";
            out << "    char text[4096];\n";
            out << "    int scroll_y;\n";
            out << "} " << sn << ";\n\n";
        } else if (contractType == "checkbox") {
            out << "typedef struct {\n";
            out << "    SDL_Rect rect;\n";
            out << "    SDL_Rect base_rect;\n";
            out << "    const char *text;\n";
            out << "    bool checked;\n";
            out << "} " << sn << ";\n\n";
        } else if (contractType == "slider") {
            out << "typedef struct {\n";
            out << "    SDL_Rect rect;\n";
            out << "    SDL_Rect base_rect;\n";
            out << "    int min_val, max_val, value;\n";
            out << "    bool dragging;\n";
            out << "} " << sn << ";\n\n";
        } else if (contractType == "progress_bar") {
            out << "typedef struct {\n";
            out << "    SDL_Rect rect;\n";
            out << "    SDL_Rect base_rect;\n";
            out << "    int min_val, max_val, value;\n";
            out << "    bool show_text;\n";
            out << "} " << sn << ";\n\n";
        } else if (contractType == "panel") {
            out << "typedef struct {\n";
            out << "    SDL_Rect rect;\n";
            out << "    SDL_Rect base_rect;\n";
            out << "} " << sn << ";\n\n";
        } else {
            // Общая заглушка
            out << "typedef struct {\n";
            out << "    SDL_Rect rect;\n";
            out << "    SDL_Rect base_rect;\n";
            out << "    /* TODO: " << w->type << " fields */\n";
            out << "} " << sn << ";\n\n";
        }
    }

    // UIState
    out << "typedef struct {\n";
    out << "    DQ_UIRuntimeContext runtime;\n";
    out << "    DQ_UIBackendFont *font;\n";
    for (const auto *w : widgets) {
        QString sn = widgetStructName(w->type);
        QString varName = sanitizeName(w->name);
        out << "    " << sn << " " << varName << ";\n";
    }
    out << "} UIState;\n\n";

    // Прототипы
    out << "void ui_init(UIState *ui);\n";
    out << "void ui_apply_layout(UIState *ui, int window_width, int window_height);\n";
    out << "void ui_render(UIState *ui, DQ_UIBackendRenderer *renderer);\n";
    out << "void ui_handle_event(UIState *ui, const DQ_UIRuntimeEvent *event);\n";

    return s;
}

// --- ui.c ---

QString SDL2CodeGenerator::generateUISource(const UILayout &layout, const QString &baseName)
{
    QVector<const UIWidget *> widgets;
    collectWidgets(layout.window, widgets);

    QString s;
    QTextStream out(&s);

    auto runtimeLayoutKindLiteral = [](const QString &layoutType) -> QString {
        if (layoutType == "HBox")
            return "DQ_UIRuntimeLayout_HBox";
        if (layoutType == "VBox")
            return "DQ_UIRuntimeLayout_VBox";
        if (layoutType == "Grid")
            return "DQ_UIRuntimeLayout_Grid";
        if (layoutType == "Flow")
            return "DQ_UIRuntimeLayout_Flow";
        return "DQ_UIRuntimeLayout_None";
    };

    out << makeGeneratedLayoutBanner(layout, "UI implementation", baseName + ".c");
    out << "#include \"" << baseName << ".h\"\n";
    out << "#include \"" << baseName << "_events.h\"\n";
    out << "#include <string.h>\n\n";

    // SDL2-реализация backend boundary для окна, событий и кадра.
    out << "bool dq_ui_backend_init(DQ_UIBackendContext *backend, const char *title, int width, int height) {\n";
    out << "    if (!backend) return false;\n";
    out << "    memset(backend, 0, sizeof(DQ_UIBackendContext));\n";
    out << "    if (SDL_Init(SDL_INIT_VIDEO) < 0) {\n";
    out << "        SDL_Log(\"SDL_Init failed: %s\", SDL_GetError());\n";
    out << "        return false;\n";
    out << "    }\n";
    out << "    if (TTF_Init() < 0) {\n";
    out << "        SDL_Log(\"TTF_Init failed: %s\", TTF_GetError());\n";
    out << "        SDL_Quit();\n";
    out << "        return false;\n";
    out << "    }\n";
    out << "    backend->window = SDL_CreateWindow(\n";
    out << "        title,\n";
    out << "        SDL_WINDOWPOS_CENTERED, SDL_WINDOWPOS_CENTERED,\n";
    out << "        width, height,\n";
    out << "        SDL_WINDOW_SHOWN);\n";
    out << "    if (!backend->window) {\n";
    out << "        SDL_Log(\"CreateWindow failed: %s\", SDL_GetError());\n";
    out << "        TTF_Quit();\n";
    out << "        SDL_Quit();\n";
    out << "        return false;\n";
    out << "    }\n";
    out << "    backend->renderer = SDL_CreateRenderer(backend->window, -1,\n";
    out << "        SDL_RENDERER_ACCELERATED | SDL_RENDERER_PRESENTVSYNC);\n";
    out << "    if (!backend->renderer) {\n";
    out << "        SDL_Log(\"CreateRenderer failed: %s\", SDL_GetError());\n";
    out << "        SDL_DestroyWindow(backend->window);\n";
    out << "        backend->window = NULL;\n";
    out << "        TTF_Quit();\n";
    out << "        SDL_Quit();\n";
    out << "        return false;\n";
    out << "    }\n";
    out << "    return true;\n";
    out << "}\n\n";

    out << "void dq_ui_backend_shutdown(DQ_UIBackendContext *backend) {\n";
    out << "    if (!backend) return;\n";
    out << "    if (backend->renderer) {\n";
    out << "        SDL_DestroyRenderer(backend->renderer);\n";
    out << "        backend->renderer = NULL;\n";
    out << "    }\n";
    out << "    if (backend->window) {\n";
    out << "        SDL_DestroyWindow(backend->window);\n";
    out << "        backend->window = NULL;\n";
    out << "    }\n";
    out << "    TTF_Quit();\n";
    out << "    SDL_Quit();\n";
    out << "}\n\n";

    out << "bool dq_ui_backend_poll_event(DQ_UIBackendEvent *event) {\n";
    out << "    return event && SDL_PollEvent(event);\n";
    out << "}\n\n";

    out << "Uint32 dq_ui_backend_ticks(void) {\n";
    out << "    return SDL_GetTicks();\n";
    out << "}\n\n";

    out << "DQ_UIBackendWindow *dq_ui_backend_window(DQ_UIBackendContext *backend) {\n";
    out << "    return backend ? backend->window : NULL;\n";
    out << "}\n\n";

    out << "DQ_UIBackendRenderer *dq_ui_backend_renderer(DQ_UIBackendContext *backend) {\n";
    out << "    return backend ? backend->renderer : NULL;\n";
    out << "}\n\n";

    out << "void dq_ui_backend_window_size(DQ_UIBackendContext *backend, int *width, int *height) {\n";
    out << "    if (width) *width = 0;\n";
    out << "    if (height) *height = 0;\n";
    out << "    if (!backend || !backend->window) return;\n";
    out << "    SDL_GetWindowSize(backend->window, width, height);\n";
    out << "}\n\n";

    out << "void dq_ui_backend_release_renderer(DQ_UIBackendContext *backend) {\n";
    out << "    if (!backend || !backend->renderer) return;\n";
    out << "    SDL_DestroyRenderer(backend->renderer);\n";
    out << "    backend->renderer = NULL;\n";
    out << "}\n\n";

    out << "void dq_ui_backend_release_window(DQ_UIBackendContext *backend) {\n";
    out << "    if (!backend || !backend->window) return;\n";
    out << "    SDL_DestroyWindow(backend->window);\n";
    out << "    backend->window = NULL;\n";
    out << "}\n\n";

    out << "void dq_ui_backend_begin_frame(DQ_UIBackendContext *backend) {\n";
    out << "    if (!backend || !backend->renderer) return;\n";
    out << "    SDL_SetRenderDrawColor(backend->renderer, 30, 30, 30, 255);\n";
    out << "    SDL_RenderClear(backend->renderer);\n";
    out << "}\n\n";

    out << "void dq_ui_backend_end_frame(DQ_UIBackendContext *backend) {\n";
    out << "    if (!backend || !backend->renderer) return;\n";
    out << "    SDL_RenderPresent(backend->renderer);\n";
    out << "}\n\n";

    out << "bool dq_ui_backend_translate_event(const DQ_UIBackendEvent *backend_event,\n";
    out << "                                   DQ_UIRuntimeEvent *runtime_event) {\n";
    out << "    if (!backend_event || !runtime_event) return false;\n";
    out << "    memset(runtime_event, 0, sizeof(DQ_UIRuntimeEvent));\n";
    out << "    switch (backend_event->type) {\n";
    out << "    case SDL_QUIT:\n";
    out << "        runtime_event->kind = DQ_UIRuntimeEvent_Quit;\n";
    out << "        return true;\n";
    out << "    case SDL_MOUSEMOTION:\n";
    out << "        runtime_event->kind = DQ_UIRuntimeEvent_MouseMove;\n";
    out << "        runtime_event->mouse_x = backend_event->motion.x;\n";
    out << "        runtime_event->mouse_y = backend_event->motion.y;\n";
    out << "        return true;\n";
    out << "    case SDL_MOUSEBUTTONDOWN:\n";
    out << "        runtime_event->kind = DQ_UIRuntimeEvent_MouseDown;\n";
    out << "        runtime_event->mouse_x = backend_event->button.x;\n";
    out << "        runtime_event->mouse_y = backend_event->button.y;\n";
    out << "        return true;\n";
    out << "    case SDL_MOUSEBUTTONUP:\n";
    out << "        runtime_event->kind = DQ_UIRuntimeEvent_MouseUp;\n";
    out << "        runtime_event->mouse_x = backend_event->button.x;\n";
    out << "        runtime_event->mouse_y = backend_event->button.y;\n";
    out << "        return true;\n";
    out << "    case SDL_MOUSEWHEEL:\n";
    out << "        runtime_event->kind = DQ_UIRuntimeEvent_MouseWheel;\n";
    out << "        runtime_event->wheel_delta_y = backend_event->wheel.y;\n";
    out << "        SDL_GetMouseState(&runtime_event->mouse_x, &runtime_event->mouse_y);\n";
    out << "        return true;\n";
    out << "    case SDL_TEXTINPUT:\n";
    out << "        runtime_event->kind = DQ_UIRuntimeEvent_TextInput;\n";
    out << "        strncpy(runtime_event->text, backend_event->text.text, sizeof(runtime_event->text) - 1);\n";
    out << "        runtime_event->text[sizeof(runtime_event->text) - 1] = '\\0';\n";
    out << "        return true;\n";
    out << "    case SDL_KEYDOWN:\n";
    out << "        if (backend_event->key.keysym.sym == SDLK_BACKSPACE) {\n";
    out << "            runtime_event->kind = DQ_UIRuntimeEvent_KeyBackspace;\n";
    out << "            return true;\n";
    out << "        }\n";
    out << "        return false;\n";
    out << "    default:\n";
    out << "        return false;\n";
    out << "    }\n";
    out << "}\n\n";

    out << "static bool dq_ui_runtime_point_in_rect(const SDL_Rect *rect, int x, int y) {\n";
    out << "    if (!rect) return false;\n";
    out << "    SDL_Point point = {x, y};\n";
    out << "    return SDL_PointInRect(&point, rect);\n";
    out << "}\n\n";

    out << "static SDL_Rect dq_ui_runtime_rect_from_base(const SDL_Rect *parent_rect,\n";
    out << "                                              const SDL_Rect *base_rect) {\n";
    out << "    SDL_Rect rect = {0, 0, 0, 0};\n";
    out << "    if (!base_rect) return rect;\n";
    out << "    rect = *base_rect;\n";
    out << "    if (parent_rect) {\n";
    out << "        rect.x += parent_rect->x;\n";
    out << "        rect.y += parent_rect->y;\n";
    out << "    }\n";
    out << "    return rect;\n";
    out << "}\n\n";

    out << "static void dq_ui_runtime_apply_anchor_spec(SDL_Rect *rect,\n";
    out << "                                            const SDL_Rect *parent_rect,\n";
    out << "                                            const SDL_Rect *base_rect,\n";
    out << "                                            const DQ_UIRuntimeAnchorSpec *spec) {\n";
    out << "    if (!rect || !base_rect) return;\n";
    out << "    *rect = dq_ui_runtime_rect_from_base(parent_rect, base_rect);\n";
    out << "    if (!parent_rect || !spec) return;\n";
    out << "    int x = rect->x;\n";
    out << "    int y = rect->y;\n";
    out << "    int w = rect->w;\n";
    out << "    int h = rect->h;\n";
    out << "    int parent_w = parent_rect->w;\n";
    out << "    int parent_h = parent_rect->h;\n";
    out << "    if (spec->left && spec->right) {\n";
    out << "        x = parent_rect->x + spec->left_margin;\n";
    out << "        w = parent_w - spec->left_margin - spec->right_margin;\n";
    out << "    } else if (spec->left) {\n";
    out << "        x = parent_rect->x + spec->left_margin;\n";
    out << "    } else if (spec->right) {\n";
    out << "        x = parent_rect->x + parent_w - spec->right_margin - w;\n";
    out << "    } else if (spec->hcenter) {\n";
    out << "        x = parent_rect->x + (parent_w - w) / 2;\n";
    out << "    }\n";
    out << "    if (spec->top && spec->bottom) {\n";
    out << "        y = parent_rect->y + spec->top_margin;\n";
    out << "        h = parent_h - spec->top_margin - spec->bottom_margin;\n";
    out << "    } else if (spec->top) {\n";
    out << "        y = parent_rect->y + spec->top_margin;\n";
    out << "    } else if (spec->bottom) {\n";
    out << "        y = parent_rect->y + parent_h - spec->bottom_margin - h;\n";
    out << "    } else if (spec->vcenter) {\n";
    out << "        y = parent_rect->y + (parent_h - h) / 2;\n";
    out << "    }\n";
    out << "    rect->x = x;\n";
    out << "    rect->y = y;\n";
    out << "    rect->w = w;\n";
    out << "    rect->h = h;\n";
    out << "}\n\n";

    out << "static void dq_ui_runtime_apply_hbox(const SDL_Rect *parent_rect,\n";
    out << "                                     SDL_Rect **child_rects,\n";
    out << "                                     int child_count,\n";
    out << "                                     int margin,\n";
    out << "                                     int spacing) {\n";
    out << "    if (!parent_rect || !child_rects || child_count <= 0) return;\n";
    out << "    int available_width = parent_rect->w - 2 * margin;\n";
    out << "    int total_spacing = spacing * (child_count - 1);\n";
    out << "    int child_width = child_count > 0 ? (available_width - total_spacing) / child_count : 0;\n";
    out << "    int child_height = parent_rect->h - 2 * margin;\n";
    out << "    int x = parent_rect->x + margin;\n";
    out << "    for (int i = 0; i < child_count; ++i) {\n";
    out << "        if (!child_rects[i]) continue;\n";
    out << "        child_rects[i]->x = x;\n";
    out << "        child_rects[i]->y = parent_rect->y + margin;\n";
    out << "        child_rects[i]->w = child_width;\n";
    out << "        child_rects[i]->h = child_height;\n";
    out << "        x += child_width + spacing;\n";
    out << "    }\n";
    out << "}\n\n";

    out << "static void dq_ui_runtime_apply_vbox(const SDL_Rect *parent_rect,\n";
    out << "                                     SDL_Rect **child_rects,\n";
    out << "                                     int child_count,\n";
    out << "                                     int margin,\n";
    out << "                                     int spacing) {\n";
    out << "    if (!parent_rect || !child_rects || child_count <= 0) return;\n";
    out << "    int available_height = parent_rect->h - 2 * margin;\n";
    out << "    int total_spacing = spacing * (child_count - 1);\n";
    out << "    int child_height = child_count > 0 ? (available_height - total_spacing) / child_count : 0;\n";
    out << "    int child_width = parent_rect->w - 2 * margin;\n";
    out << "    int y = parent_rect->y + margin;\n";
    out << "    for (int i = 0; i < child_count; ++i) {\n";
    out << "        if (!child_rects[i]) continue;\n";
    out << "        child_rects[i]->x = parent_rect->x + margin;\n";
    out << "        child_rects[i]->y = y;\n";
    out << "        child_rects[i]->w = child_width;\n";
    out << "        child_rects[i]->h = child_height;\n";
    out << "        y += child_height + spacing;\n";
    out << "    }\n";
    out << "}\n\n";

    out << "static void dq_ui_runtime_apply_grid(const SDL_Rect *parent_rect,\n";
    out << "                                     SDL_Rect **child_rects,\n";
    out << "                                     int child_count,\n";
    out << "                                     int margin,\n";
    out << "                                     int spacing) {\n";
    out << "    if (!parent_rect || !child_rects || child_count <= 0) return;\n";
    out << "    int cols = 1;\n";
    out << "    while (cols * cols < child_count) ++cols;\n";
    out << "    int rows = (child_count + cols - 1) / cols;\n";
    out << "    int available_width = parent_rect->w - 2 * margin;\n";
    out << "    int available_height = parent_rect->h - 2 * margin;\n";
    out << "    int cell_width = cols > 0 ? (available_width - spacing * (cols - 1)) / cols : available_width;\n";
    out << "    int cell_height = rows > 0 ? (available_height - spacing * (rows - 1)) / rows : available_height;\n";
    out << "    for (int i = 0; i < child_count; ++i) {\n";
    out << "        if (!child_rects[i]) continue;\n";
    out << "        int col = i % cols;\n";
    out << "        int row = i / cols;\n";
    out << "        child_rects[i]->x = parent_rect->x + margin + col * (cell_width + spacing);\n";
    out << "        child_rects[i]->y = parent_rect->y + margin + row * (cell_height + spacing);\n";
    out << "        child_rects[i]->w = cell_width;\n";
    out << "        child_rects[i]->h = cell_height;\n";
    out << "    }\n";
    out << "}\n\n";

    out << "static void dq_ui_runtime_apply_flow(const SDL_Rect *parent_rect,\n";
    out << "                                     SDL_Rect **child_rects,\n";
    out << "                                     int child_count,\n";
    out << "                                     int margin,\n";
    out << "                                     int spacing) {\n";
    out << "    if (!parent_rect || !child_rects || child_count <= 0) return;\n";
    out << "    int container_width = parent_rect->w - 2 * margin;\n";
    out << "    int x = parent_rect->x + margin;\n";
    out << "    int y = parent_rect->y + margin;\n";
    out << "    int row_height = 0;\n";
    out << "    for (int i = 0; i < child_count; ++i) {\n";
    out << "        SDL_Rect *child = child_rects[i];\n";
    out << "        if (!child) continue;\n";
    out << "        if (x + child->w > parent_rect->x + margin + container_width && x > parent_rect->x + margin) {\n";
    out << "            x = parent_rect->x + margin;\n";
    out << "            y += row_height + spacing;\n";
    out << "            row_height = 0;\n";
    out << "        }\n";
    out << "        child->x = x;\n";
    out << "        child->y = y;\n";
    out << "        x += child->w + spacing;\n";
    out << "        if (child->h > row_height) row_height = child->h;\n";
    out << "    }\n";
    out << "}\n\n";

    out << "static void dq_ui_runtime_apply_layout_spec(const SDL_Rect *parent_rect,\n";
    out << "                                           SDL_Rect **child_rects,\n";
    out << "                                           int child_count,\n";
    out << "                                           const DQ_UIRuntimeLayoutSpec *spec) {\n";
    out << "    if (!spec || spec->kind == DQ_UIRuntimeLayout_None) return;\n";
    out << "    switch (spec->kind) {\n";
    out << "    case DQ_UIRuntimeLayout_HBox:\n";
    out << "        dq_ui_runtime_apply_hbox(parent_rect, child_rects, child_count, spec->margin, spec->spacing);\n";
    out << "        break;\n";
    out << "    case DQ_UIRuntimeLayout_VBox:\n";
    out << "        dq_ui_runtime_apply_vbox(parent_rect, child_rects, child_count, spec->margin, spec->spacing);\n";
    out << "        break;\n";
    out << "    case DQ_UIRuntimeLayout_Grid:\n";
    out << "        dq_ui_runtime_apply_grid(parent_rect, child_rects, child_count, spec->margin, spec->spacing);\n";
    out << "        break;\n";
    out << "    case DQ_UIRuntimeLayout_Flow:\n";
    out << "        dq_ui_runtime_apply_flow(parent_rect, child_rects, child_count, spec->margin, spec->spacing);\n";
    out << "        break;\n";
    out << "    default:\n";
    out << "        break;\n";
    out << "    }\n";
    out << "}\n\n";

    // Явные runtime spec-объекты фиксируют layout/anchor semantics отдельно
    // от кода обхода дерева и позволяют переиспользовать одну модель размещения.
    out << "static const DQ_UIRuntimeLayoutSpec dq_ui_layoutspec_root = {"
        << runtimeLayoutKindLiteral(layout.window.layout) << ", "
        << layout.window.properties.value("margin", 10).toInt() << ", "
        << layout.window.properties.value("spacing", 5).toInt() << "};\n";

    for (const auto *w : widgets) {
        const QString varName = sanitizeName(w->name);
        out << "static const DQ_UIRuntimeLayoutSpec dq_ui_layoutspec_" << varName << " = {"
            << runtimeLayoutKindLiteral(w->layout) << ", "
            << w->properties.value("margin", 10).toInt() << ", "
            << w->properties.value("spacing", 5).toInt() << "};\n";
        out << "static const DQ_UIRuntimeAnchorSpec dq_ui_anchorspec_" << varName << " = {"
            << (w->anchors.left ? "true" : "false") << ", "
            << (w->anchors.right ? "true" : "false") << ", "
            << (w->anchors.top ? "true" : "false") << ", "
            << (w->anchors.bottom ? "true" : "false") << ", "
            << (w->anchors.hCenter ? "true" : "false") << ", "
            << (w->anchors.vCenter ? "true" : "false") << ", "
            << static_cast<int>(w->anchors.leftMargin) << ", "
            << static_cast<int>(w->anchors.rightMargin) << ", "
            << static_cast<int>(w->anchors.topMargin) << ", "
            << static_cast<int>(w->anchors.bottomMargin) << "};\n";
    }
    out << "\n";

    out << "static bool dq_ui_runtime_widget_is_button(DQ_UIWidgetId widget_id) {\n";
    out << "    switch (widget_id) {\n";
    for (const auto *w : widgets) {
        if (widgetMatchesContract(*w, "button")) {
            out << "    case DQ_UIWidget_" << sanitizeName(w->name) << ":\n";
            out << "        return true;\n";
        }
    }
    out << "    default:\n";
    out << "        return false;\n";
    out << "    }\n";
    out << "}\n\n";

    out << "static bool dq_ui_runtime_widget_is_checkbox(DQ_UIWidgetId widget_id) {\n";
    out << "    switch (widget_id) {\n";
    for (const auto *w : widgets) {
        if (widgetMatchesContract(*w, "checkbox")) {
            out << "    case DQ_UIWidget_" << sanitizeName(w->name) << ":\n";
            out << "        return true;\n";
        }
    }
    out << "    default:\n";
    out << "        return false;\n";
    out << "    }\n";
    out << "}\n\n";

    out << "static bool dq_ui_runtime_widget_is_text_field(DQ_UIWidgetId widget_id) {\n";
    out << "    switch (widget_id) {\n";
    for (const auto *w : widgets) {
        if (widgetMatchesContract(*w, "text_field")) {
            out << "    case DQ_UIWidget_" << sanitizeName(w->name) << ":\n";
            out << "        return true;\n";
        }
    }
    out << "    default:\n";
    out << "        return false;\n";
    out << "    }\n";
    out << "}\n\n";

    out << "static bool dq_ui_runtime_widget_is_text_area(DQ_UIWidgetId widget_id) {\n";
    out << "    switch (widget_id) {\n";
    for (const auto *w : widgets) {
        if (widgetMatchesContract(*w, "text_area")) {
            out << "    case DQ_UIWidget_" << sanitizeName(w->name) << ":\n";
            out << "        return true;\n";
        }
    }
    out << "    default:\n";
    out << "        return false;\n";
    out << "    }\n";
    out << "}\n\n";

    out << "static bool dq_ui_runtime_widget_is_slider(DQ_UIWidgetId widget_id) {\n";
    out << "    switch (widget_id) {\n";
    for (const auto *w : widgets) {
        if (widgetMatchesContract(*w, "slider")) {
            out << "    case DQ_UIWidget_" << sanitizeName(w->name) << ":\n";
            out << "        return true;\n";
        }
    }
    out << "    default:\n";
    out << "        return false;\n";
    out << "    }\n";
    out << "}\n\n";

    out << "static DQ_UIWidgetId dq_ui_runtime_hit_test(const UIState *ui, int x, int y) {\n";
    out << "    if (!ui) return DQ_UIWidget_None;\n";
    for (int i = widgets.size() - 1; i >= 0; --i) {
        const auto *w = widgets.at(i);
        const QString contractType = widgetContractType(*w);
        if (contractType == "button" || contractType == "checkbox" ||
            contractType == "text_field" || contractType == "text_area" ||
            contractType == "slider") {
            out << "    if (dq_ui_runtime_point_in_rect(&ui->" << sanitizeName(w->name)
                << ".rect, x, y)) return DQ_UIWidget_" << sanitizeName(w->name) << ";\n";
        }
    }
    out << "    return DQ_UIWidget_None;\n";
    out << "}\n\n";

    out << "static void dq_ui_runtime_sync_state(UIState *ui) {\n";
    out << "    if (!ui) return;\n";
    for (const auto *w : widgets) {
        const QString varName = sanitizeName(w->name);
        const QString contractType = widgetContractType(*w);
        if (contractType == "button") {
            out << "    ui->" << varName << ".hovered = ui->runtime.hovered_widget == DQ_UIWidget_" << varName << ";\n";
            out << "    ui->" << varName << ".pressed = ui->runtime.active_widget == DQ_UIWidget_" << varName << ";\n";
        } else if (contractType == "text_field") {
            out << "    ui->" << varName << ".focused = ui->runtime.focused_widget == DQ_UIWidget_" << varName << ";\n";
        } else if (contractType == "slider") {
            out << "    ui->" << varName << ".dragging = ui->runtime.active_widget == DQ_UIWidget_" << varName << ";\n";
        }
    }
    out << "}\n\n";

    out << "static void dq_ui_runtime_dispatch_click(UIState *ui, DQ_UIWidgetId widget_id) {\n";
    out << "    if (!ui) return;\n";
    out << "    switch (widget_id) {\n";
    for (const auto *w : widgets) {
        if (widgetMatchesContract(*w, "button")) {
            out << "    case DQ_UIWidget_" << sanitizeName(w->name) << ":\n";
            if (w->events.contains("onClick")) {
                out << "        " << sanitizeName(w->events["onClick"]) << "(ui);\n";
            } else {
                out << "        /* TODO: onClick handler */\n";
            }
            out << "        break;\n";
        }
    }
    out << "    default:\n";
    out << "        break;\n";
    out << "    }\n";
    out << "}\n\n";

    out << "static void dq_ui_runtime_toggle_checkbox(UIState *ui, DQ_UIWidgetId widget_id) {\n";
    out << "    if (!ui) return;\n";
    out << "    switch (widget_id) {\n";
    for (const auto *w : widgets) {
        if (widgetMatchesContract(*w, "checkbox")) {
            const QString varName = sanitizeName(w->name);
            out << "    case DQ_UIWidget_" << varName << ":\n";
            out << "        ui->" << varName << ".checked = !ui->" << varName << ".checked;\n";
            out << "        break;\n";
        }
    }
    out << "    default:\n";
    out << "        break;\n";
    out << "    }\n";
    out << "}\n\n";

    out << "static void dq_ui_runtime_append_text(UIState *ui, DQ_UIWidgetId widget_id, const char *text) {\n";
    out << "    if (!ui || !text || !text[0]) return;\n";
    out << "    switch (widget_id) {\n";
    for (const auto *w : widgets) {
        if (widgetMatchesContract(*w, "text_field")) {
            const QString varName = sanitizeName(w->name);
            out << "    case DQ_UIWidget_" << varName << ":\n";
            out << "    {\n";
            out << "        int len = (int)strlen(ui->" << varName << ".text);\n";
            out << "        if (len < 255) {\n";
            out << "            strcat(ui->" << varName << ".text, text);\n";
            out << "        }\n";
            out << "        break;\n";
            out << "    }\n";
        }
    }
    out << "    default:\n";
    out << "        break;\n";
    out << "    }\n";
    out << "}\n\n";

    out << "static void dq_ui_runtime_backspace(UIState *ui, DQ_UIWidgetId widget_id) {\n";
    out << "    if (!ui) return;\n";
    out << "    switch (widget_id) {\n";
    for (const auto *w : widgets) {
        if (widgetMatchesContract(*w, "text_field")) {
            const QString varName = sanitizeName(w->name);
            out << "    case DQ_UIWidget_" << varName << ":\n";
            out << "    {\n";
            out << "        int len = (int)strlen(ui->" << varName << ".text);\n";
            out << "        if (len > 0) ui->" << varName << ".text[len - 1] = '\\0';\n";
            out << "        break;\n";
            out << "    }\n";
        }
    }
    out << "    default:\n";
    out << "        break;\n";
    out << "    }\n";
    out << "}\n\n";

    out << "static void dq_ui_runtime_apply_wheel(UIState *ui, DQ_UIWidgetId widget_id, int wheel_delta_y) {\n";
    out << "    if (!ui) return;\n";
    out << "    switch (widget_id) {\n";
    for (const auto *w : widgets) {
        if (widgetMatchesContract(*w, "text_area")) {
            const QString varName = sanitizeName(w->name);
            out << "    case DQ_UIWidget_" << varName << ":\n";
            out << "        ui->" << varName << ".scroll_y -= wheel_delta_y * 20;\n";
            out << "        if (ui->" << varName << ".scroll_y < 0) ui->" << varName << ".scroll_y = 0;\n";
            out << "        break;\n";
        }
    }
    out << "    default:\n";
    out << "        break;\n";
    out << "    }\n";
    out << "}\n\n";

    out << "static void dq_ui_runtime_update_slider(UIState *ui, DQ_UIWidgetId widget_id, int mouse_x) {\n";
    out << "    if (!ui) return;\n";
    out << "    switch (widget_id) {\n";
    for (const auto *w : widgets) {
        if (widgetMatchesContract(*w, "slider")) {
            const QString varName = sanitizeName(w->name);
            out << "    case DQ_UIWidget_" << varName << ":\n";
            out << "    {\n";
            out << "        int rel = mouse_x - ui->" << varName << ".rect.x - 8;\n";
            out << "        int range = ui->" << varName << ".rect.w - 16;\n";
            out << "        if (range > 0) {\n";
            out << "            int val = ui->" << varName << ".min_val + rel * (ui->" << varName << ".max_val - ui->" << varName << ".min_val) / range;\n";
            out << "            if (val < ui->" << varName << ".min_val) val = ui->" << varName << ".min_val;\n";
            out << "            if (val > ui->" << varName << ".max_val) val = ui->" << varName << ".max_val;\n";
            out << "            ui->" << varName << ".value = val;\n";
            out << "        }\n";
            out << "        break;\n";
            out << "    }\n";
        }
    }
    out << "    default:\n";
    out << "        break;\n";
    out << "    }\n";
    out << "}\n\n";

    // Вспомогательная функция рендеринга текста через TTF
    out << "static void render_text(DQ_UIBackendRenderer *r, DQ_UIBackendFont *font,\n";
    out << "                        const char *text, int x, int y, SDL_Color color) {\n";
    out << "    if (!font || !text || !text[0]) return;\n";
    out << "    SDL_Surface *surf = TTF_RenderUTF8_Blended(font, text, color);\n";
    out << "    if (!surf) return;\n";
    out << "    SDL_Texture *tex = SDL_CreateTextureFromSurface(r, surf);\n";
    out << "    SDL_Rect dst = {x, y, surf->w, surf->h};\n";
    out << "    SDL_RenderCopy(r, tex, NULL, &dst);\n";
    out << "    SDL_DestroyTexture(tex);\n";
    out << "    SDL_FreeSurface(surf);\n";
    out << "}\n\n";

    // Функции рисования для каждого типа
    QSet<QString> emittedRenders;
    for (const auto *w : widgets) {
        const QString contractType = widgetContractType(*w);
        if (emittedRenders.contains(contractType)) continue;
        emittedRenders.insert(contractType);

        QString sn = widgetStructName(w->type);
        QString fn = widgetRenderFunc(w->type);

        if (contractType == "button") {
            out << "static void " << fn << "(" << sn << " *btn, DQ_UIBackendRenderer *r, DQ_UIBackendFont *font) {\n";
            out << "    SDL_SetRenderDrawColor(r, btn->pressed ? 80 : (btn->hovered ? 70 : 61),\n";
            out << "                              btn->pressed ? 80 : (btn->hovered ? 70 : 61),\n";
            out << "                              btn->pressed ? 80 : (btn->hovered ? 70 : 61), 255);\n";
            out << "    SDL_RenderFillRect(r, &btn->rect);\n";
            out << "    SDL_SetRenderDrawColor(r, 100, 100, 100, 255);\n";
            out << "    SDL_RenderDrawRect(r, &btn->rect);\n";
            out << "    SDL_Color c = {220, 220, 220, 255};\n";
            out << "    render_text(r, font, btn->text, btn->rect.x + 8, btn->rect.y + 10, c);\n";
            out << "}\n\n";
        } else if (contractType == "label") {
            out << "static void " << fn << "(" << sn << " *lbl, DQ_UIBackendRenderer *r, DQ_UIBackendFont *font) {\n";
            out << "    SDL_Color c = {200, 200, 200, 255};\n";
            out << "    render_text(r, font, lbl->text, lbl->rect.x, lbl->rect.y + 5, c);\n";
            out << "}\n\n";
        } else if (contractType == "text_field") {
            out << "static void " << fn << "(" << sn << " *tf, DQ_UIBackendRenderer *r, DQ_UIBackendFont *font) {\n";
            out << "    SDL_SetRenderDrawColor(r, 50, 50, 50, 255);\n";
            out << "    SDL_RenderFillRect(r, &tf->rect);\n";
            out << "    SDL_SetRenderDrawColor(r, tf->focused ? 0 : 100,\n";
            out << "                              tf->focused ? 120 : 100,\n";
            out << "                              tf->focused ? 215 : 100, 255);\n";
            out << "    SDL_RenderDrawRect(r, &tf->rect);\n";
            out << "    const char *display = tf->text[0] ? tf->text : tf->placeholder;\n";
            out << "    SDL_Color c = tf->text[0] ? (SDL_Color){220,220,220,255} : (SDL_Color){120,120,120,255};\n";
            out << "    render_text(r, font, display, tf->rect.x + 4, tf->rect.y + 6, c);\n";
            out << "}\n\n";
        } else if (contractType == "text_area") {
            out << "static void " << fn << "(" << sn << " *ta, DQ_UIBackendRenderer *r, DQ_UIBackendFont *font) {\n";
            out << "    SDL_SetRenderDrawColor(r, 40, 40, 40, 255);\n";
            out << "    SDL_RenderFillRect(r, &ta->rect);\n";
            out << "    SDL_SetRenderDrawColor(r, 80, 80, 80, 255);\n";
            out << "    SDL_RenderDrawRect(r, &ta->rect);\n";
            out << "    if (!font || !ta->text[0]) return;\n";
            out << "    int line_h = TTF_FontLineSkip(font);\n";
            out << "    int y = ta->rect.y + 4 - ta->scroll_y;\n";
            out << "    char *line_start = ta->text;\n";
            out << "    while (*line_start) {\n";
            out << "        char *nl = strchr(line_start, '\\n');\n";
            out << "        int len = nl ? (int)(nl - line_start) : (int)strlen(line_start);\n";
            out << "        if (len > 0 && y + line_h > ta->rect.y && y < ta->rect.y + ta->rect.h) {\n";
            out << "            char buf[512];\n";
            out << "            int copy = len < 511 ? len : 511;\n";
            out << "            memcpy(buf, line_start, copy);\n";
            out << "            buf[copy] = '\\0';\n";
            out << "            SDL_Color c = {200, 200, 200, 255};\n";
            out << "            render_text(r, font, buf, ta->rect.x + 4, y, c);\n";
            out << "        }\n";
            out << "        y += line_h;\n";
            out << "        line_start += len + (nl ? 1 : 0);\n";
            out << "        if (!nl) break;\n";
            out << "    }\n";
            out << "}\n\n";
        } else if (contractType == "checkbox") {
            out << "static void " << fn << "(" << sn << " *cb, DQ_UIBackendRenderer *r, DQ_UIBackendFont *font) {\n";
            out << "    SDL_Rect box = {cb->rect.x, cb->rect.y + (cb->rect.h - 16) / 2, 16, 16};\n";
            out << "    SDL_SetRenderDrawColor(r, 50, 50, 50, 255);\n";
            out << "    SDL_RenderFillRect(r, &box);\n";
            out << "    SDL_SetRenderDrawColor(r, 120, 120, 120, 255);\n";
            out << "    SDL_RenderDrawRect(r, &box);\n";
            out << "    if (cb->checked) {\n";
            out << "        SDL_SetRenderDrawColor(r, 0, 180, 80, 255);\n";
            out << "        SDL_RenderDrawLine(r, box.x + 3, box.y + 8, box.x + 6, box.y + 12);\n";
            out << "        SDL_RenderDrawLine(r, box.x + 6, box.y + 12, box.x + 12, box.y + 3);\n";
            out << "    }\n";
            out << "    SDL_Color c = {200, 200, 200, 255};\n";
            out << "    render_text(r, font, cb->text, cb->rect.x + 22, cb->rect.y + 5, c);\n";
            out << "}\n\n";
        } else if (contractType == "slider") {
            out << "static void " << fn << "(" << sn << " *sl, DQ_UIBackendRenderer *r, DQ_UIBackendFont *font) {\n";
            out << "    (void)font;\n";
            out << "    int track_y = sl->rect.y + sl->rect.h / 2;\n";
            out << "    SDL_SetRenderDrawColor(r, 80, 80, 80, 255);\n";
            out << "    SDL_Rect track = {sl->rect.x + 8, track_y - 2, sl->rect.w - 16, 4};\n";
            out << "    SDL_RenderFillRect(r, &track);\n";
            out << "    int range = sl->max_val - sl->min_val;\n";
            out << "    int knob_x = sl->rect.x + 8;\n";
            out << "    if (range > 0)\n";
            out << "        knob_x += (sl->value - sl->min_val) * (sl->rect.w - 16) / range;\n";
            out << "    SDL_Rect knob = {knob_x - 6, track_y - 6, 12, 12};\n";
            out << "    SDL_SetRenderDrawColor(r, 200, 200, 200, 255);\n";
            out << "    SDL_RenderFillRect(r, &knob);\n";
            out << "}\n\n";
        } else if (contractType == "progress_bar") {
            out << "static void " << fn << "(" << sn << " *pb, DQ_UIBackendRenderer *r, DQ_UIBackendFont *font) {\n";
            out << "    (void)font;\n";
            out << "    SDL_SetRenderDrawColor(r, 50, 50, 50, 255);\n";
            out << "    SDL_RenderFillRect(r, &pb->rect);\n";
            out << "    int range = pb->max_val - pb->min_val;\n";
            out << "    if (range > 0) {\n";
            out << "        int fill_w = (pb->value - pb->min_val) * pb->rect.w / range;\n";
            out << "        SDL_Rect fill = {pb->rect.x, pb->rect.y, fill_w, pb->rect.h};\n";
            out << "        SDL_SetRenderDrawColor(r, 0, 120, 215, 255);\n";
            out << "        SDL_RenderFillRect(r, &fill);\n";
            out << "    }\n";
            out << "    SDL_SetRenderDrawColor(r, 80, 80, 80, 255);\n";
            out << "    SDL_RenderDrawRect(r, &pb->rect);\n";
            out << "}\n\n";
        } else if (contractType == "panel") {
            out << "static void " << fn << "(" << sn << " *pnl, DQ_UIBackendRenderer *r, DQ_UIBackendFont *font) {\n";
            out << "    (void)font;\n";
            out << "    SDL_SetRenderDrawColor(r, 45, 45, 45, 255);\n";
            out << "    SDL_RenderFillRect(r, &pnl->rect);\n";
            out << "    SDL_SetRenderDrawColor(r, 80, 80, 80, 255);\n";
            out << "    SDL_RenderDrawRect(r, &pnl->rect);\n";
            out << "}\n\n";
        } else {
            out << "static void " << fn << "(" << sn << " *w, DQ_UIBackendRenderer *r, DQ_UIBackendFont *font) {\n";
            out << "    (void)w; (void)r; (void)font;\n";
            out << "    /* TODO: implement " << w->type << " rendering */\n";
            out << "}\n\n";
        }
    }

    // ui_init
    out << "void ui_init(UIState *ui) {\n";
    out << "    memset(ui, 0, sizeof(UIState));\n\n";

    // Загрузка системного шрифта
    out << "    // Поиск системного шрифта\n";
    out << "    const char *font_paths[] = {\n";
    out << "        \"/usr/share/fonts/truetype/dejavu/DejaVuSans.ttf\",\n";
    out << "        \"/usr/share/fonts/TTF/DejaVuSans.ttf\",\n";
    out << "        \"/usr/share/fonts/truetype/liberation/LiberationSans-Regular.ttf\",\n";
    out << "        \"C:\\\\Windows\\\\Fonts\\\\arial.ttf\",\n";
    out << "        NULL\n";
    out << "    };\n";
    out << "    for (int i = 0; font_paths[i]; i++) {\n";
    out << "        ui->font = TTF_OpenFont(font_paths[i], 14);\n";
    out << "        if (ui->font) break;\n";
    out << "    }\n\n";

    for (const auto *w : widgets) {
        QString varName = sanitizeName(w->name);
        int x = static_cast<int>(w->geometry.x());
        int y = static_cast<int>(w->geometry.y());
        int ww = static_cast<int>(w->geometry.width());
        int hh = static_cast<int>(w->geometry.height());
        const QString contractType = widgetContractType(*w);
        out << "    ui->" << varName << ".rect = (SDL_Rect){" << x << ", " << y << ", " << ww << ", " << hh << "};\n";
        out << "    ui->" << varName << ".base_rect = ui->" << varName << ".rect;\n";

        if (contractType == "button" || contractType == "checkbox") {
            QString text = w->properties.value("text", w->name).toString();
            out << "    ui->" << varName << ".text = \"" << text << "\";\n";
        }
        if (contractType == "label") {
            QString text = w->properties.value("text", w->name).toString();
            out << "    strncpy(ui->" << varName << ".text, \"" << text << "\", 63);\n";
            out << "    ui->" << varName << ".text[63] = '\\0';\n";
        }
        if (contractType == "text_field") {
            QString placeholder = w->properties.value("placeholder", "").toString();
            out << "    ui->" << varName << ".placeholder = \"" << placeholder << "\";\n";
        }
        if (contractType == "text_area") {
            out << "    memset(ui->" << varName << ".text, 0, sizeof(ui->" << varName << ".text));\n";
            out << "    ui->" << varName << ".scroll_y = 0;\n";
        }
        if (contractType == "slider") {
            int minV = w->properties.value("min", 0).toInt();
            int maxV = w->properties.value("max", 100).toInt();
            int val = w->properties.value("value", 50).toInt();
            out << "    ui->" << varName << ".min_val = " << minV << ";\n";
            out << "    ui->" << varName << ".max_val = " << maxV << ";\n";
            out << "    ui->" << varName << ".value = " << val << ";\n";
        }
        if (contractType == "progress_bar") {
            int minV = w->properties.value("min", 0).toInt();
            int maxV = w->properties.value("max", 100).toInt();
            int val = w->properties.value("value", 40).toInt();
            bool showText = w->properties.value("show_text", true).toBool();
            out << "    ui->" << varName << ".min_val = " << minV << ";\n";
            out << "    ui->" << varName << ".max_val = " << maxV << ";\n";
            out << "    ui->" << varName << ".value = " << val << ";\n";
            out << "    ui->" << varName << ".show_text = " << (showText ? "true" : "false") << ";\n";
        }
    }
    out << "    ui_apply_layout(ui, "
        << static_cast<int>(layout.window.geometry.width()) << ", "
        << static_cast<int>(layout.window.geometry.height()) << ");\n";
    out << "    dq_ui_runtime_sync_state(ui);\n";
    out << "}\n\n";

    // ui_apply_layout
    out << "void ui_apply_layout(UIState *ui, int window_width, int window_height) {\n";
    out << "    if (!ui) return;\n";
    out << "    ui->runtime.window_width = window_width;\n";
    out << "    ui->runtime.window_height = window_height;\n";
    out << "    SDL_Rect dq_ui_window_rect = {0, 0, window_width, window_height};\n";

    auto emitLayoutPass = [&](const UIWidget &parent, const QString &parentRectExpr,
                              const QString &parentLayoutSpecExpr,
                              const auto &emitLayoutPassRef) -> void {
        if (parent.children.isEmpty())
            return;

        const bool hasLayout = !parent.layout.isEmpty() && parent.layout != "None";

        if (hasLayout) {
            for (const auto &child : parent.children) {
                const QString varName = sanitizeName(child.name);
                out << "    ui->" << varName << ".rect = dq_ui_runtime_rect_from_base(&"
                    << parentRectExpr << ", &ui->" << varName << ".base_rect);\n";
            }

            out << "    {\n";
            out << "        SDL_Rect *child_rects[] = {\n";
            for (const auto &child : parent.children) {
                out << "            &ui->" << sanitizeName(child.name) << ".rect,\n";
            }
            out << "        };\n";
            out << "        dq_ui_runtime_apply_layout_spec(&" << parentRectExpr
                << ", child_rects, " << parent.children.size()
                << ", &" << parentLayoutSpecExpr << ");\n";
            out << "    }\n";
        } else {
            for (const auto &child : parent.children) {
                const QString varName = sanitizeName(child.name);
                out << "    dq_ui_runtime_apply_anchor_spec(&ui->" << varName
                    << ".rect, &" << parentRectExpr
                    << ", &ui->" << varName << ".base_rect, "
                    << "&dq_ui_anchorspec_" << varName << ");\n";
            }
        }

        for (const auto &child : parent.children) {
            const QString childVarName = sanitizeName(child.name);
            emitLayoutPassRef(child,
                              QString("ui->%1.rect").arg(childVarName),
                              QString("dq_ui_layoutspec_%1").arg(childVarName),
                              emitLayoutPassRef);
        }
    };

    emitLayoutPass(layout.window, "dq_ui_window_rect", "dq_ui_layoutspec_root", emitLayoutPass);
    out << "}\n\n";

    // ui_render
    out << "void ui_render(UIState *ui, DQ_UIBackendRenderer *renderer) {\n";
    for (const auto *w : widgets) {
        QString varName = sanitizeName(w->name);
        QString fn = widgetRenderFunc(w->type);
        out << "    " << fn << "(&ui->" << varName << ", renderer, ui->font);\n";
    }
    out << "}\n\n";

    // ui_handle_event
    out << "void ui_handle_event(UIState *ui, const DQ_UIRuntimeEvent *event) {\n";
    out << "    if (!ui || !event) return;\n";
    out << "    // Runtime-модель держит hit-test, focus и active widget отдельно\n";
    out << "    // от конкретного backend и синхронизирует render-состояние виджетов.\n";
    out << "    ui->runtime.mouse_x = event->mouse_x;\n";
    out << "    ui->runtime.mouse_y = event->mouse_y;\n";
    out << "\n";
    out << "    if (event->kind == DQ_UIRuntimeEvent_MouseMove ||\n";
    out << "        event->kind == DQ_UIRuntimeEvent_MouseDown ||\n";
    out << "        event->kind == DQ_UIRuntimeEvent_MouseUp ||\n";
    out << "        event->kind == DQ_UIRuntimeEvent_MouseWheel) {\n";
    out << "        ui->runtime.hovered_widget = dq_ui_runtime_hit_test(ui, event->mouse_x, event->mouse_y);\n";
    out << "    }\n";
    out << "\n";
    out << "    switch (event->kind) {\n";
    out << "    case DQ_UIRuntimeEvent_MouseMove:\n";
    out << "        if (dq_ui_runtime_widget_is_slider(ui->runtime.active_widget)) {\n";
    out << "            dq_ui_runtime_update_slider(ui, ui->runtime.active_widget, event->mouse_x);\n";
    out << "        }\n";
    out << "        break;\n";
    out << "    case DQ_UIRuntimeEvent_MouseDown:\n";
    out << "        ui->runtime.active_widget = ui->runtime.hovered_widget;\n";
    out << "        if (dq_ui_runtime_widget_is_text_field(ui->runtime.active_widget)) {\n";
    out << "            ui->runtime.focused_widget = ui->runtime.active_widget;\n";
    out << "        } else {\n";
    out << "            ui->runtime.focused_widget = DQ_UIWidget_None;\n";
    out << "        }\n";
    out << "        if (dq_ui_runtime_widget_is_checkbox(ui->runtime.active_widget)) {\n";
    out << "            dq_ui_runtime_toggle_checkbox(ui, ui->runtime.active_widget);\n";
    out << "        }\n";
    out << "        if (dq_ui_runtime_widget_is_slider(ui->runtime.active_widget)) {\n";
    out << "            dq_ui_runtime_update_slider(ui, ui->runtime.active_widget, event->mouse_x);\n";
    out << "        }\n";
    out << "        break;\n";
    out << "    case DQ_UIRuntimeEvent_MouseUp:\n";
    out << "        if (dq_ui_runtime_widget_is_button(ui->runtime.active_widget) &&\n";
    out << "            ui->runtime.active_widget == ui->runtime.hovered_widget) {\n";
    out << "            dq_ui_runtime_dispatch_click(ui, ui->runtime.active_widget);\n";
    out << "        }\n";
    out << "        ui->runtime.active_widget = DQ_UIWidget_None;\n";
    out << "        break;\n";
    out << "    case DQ_UIRuntimeEvent_MouseWheel:\n";
    out << "        if (dq_ui_runtime_widget_is_text_area(ui->runtime.hovered_widget)) {\n";
    out << "            dq_ui_runtime_apply_wheel(ui, ui->runtime.hovered_widget, event->wheel_delta_y);\n";
    out << "        }\n";
    out << "        break;\n";
    out << "    case DQ_UIRuntimeEvent_TextInput:\n";
    out << "        dq_ui_runtime_append_text(ui, ui->runtime.focused_widget, event->text);\n";
    out << "        break;\n";
    out << "    case DQ_UIRuntimeEvent_KeyBackspace:\n";
    out << "        dq_ui_runtime_backspace(ui, ui->runtime.focused_widget);\n";
    out << "        break;\n";
    out << "    default:\n";
    out << "        break;\n";
    out << "    }\n";
    out << "\n";
    out << "    dq_ui_runtime_sync_state(ui);\n";
    out << "}\n";
    return s;
}

// --- events.h ---

QString SDL2CodeGenerator::generateEventsHeader(const UILayout &layout, const QString &baseName)
{
    QMap<QString, QString> events;
    collectEvents(layout.window, events);

    QString s;
    QTextStream out(&s);

    out << makeGeneratedLayoutBanner(layout, "event header", baseName + "_events.h");
    out << "#pragma once\n\n";
    out << "#include \"" << baseName << ".h\"\n\n";

    for (auto it = events.begin(); it != events.end(); ++it) {
        out << "void " << sanitizeName(it.key()) << "(UIState *ui);\n";
    }

    out << "void ui_update(UIState *ui, Uint32 delta_ms);\n";

    return s;
}

// --- events.c ---

QString SDL2CodeGenerator::generateEventsSource(const UILayout &layout, const QString &baseName)
{
    QMap<QString, QString> events;
    collectEvents(layout.window, events);

    QString s;
    QTextStream out(&s);

    out << makeGeneratedLayoutBanner(layout, "event implementation", baseName + "_events.c");
    out << "#include \"" << baseName << "_events.h\"\n";
    out << "#include <stdio.h>\n\n";

    for (auto it = events.begin(); it != events.end(); ++it) {
        out << "void " << sanitizeName(it.key()) << "(UIState *ui) {\n";
        out << "    (void)ui;\n";
        out << "    /* TODO: implement " << it.key() << " handler for event '" << it.value() << "' */\n";
        out << "}\n\n";
    }

    out << "void ui_update(UIState *ui, Uint32 delta_ms) {\n";
    out << "    (void)ui; (void)delta_ms;\n";
    out << "}\n";

    return s;
}

} // namespace DeltaQ
