// Компилятор графов — реализация
#include "GraphCompiler.h"
#include "IR.h"
#include "../core/ModuleRegistry.h"
#include "../core/GraphStore.h"
#include "../uiDesigner/UIModuleFactory.h"
#include <deltaq/Graph.h>
#include <deltaq/Module.h>

#include <QTextStream>
#include <QSet>

namespace DeltaQ {

namespace {

int emittedLineCount(const IRInstruction &instr)
{
    switch (instr.type) {
    case IRInstruction::RawCode: {
        QString raw = instr.rawCode;
        if (!raw.endsWith('\n'))
            raw += '\n';
        int count = 0;
        const auto lines = raw.split('\n');
        for (int i = 0; i < lines.size(); ++i) {
            if (i == lines.size() - 1 && lines[i].isEmpty())
                continue;
            count++;
        }
        return qMax(1, count);
    }
    case IRInstruction::Comment:
    case IRInstruction::DeclareVar:
    case IRInstruction::Call:
    case IRInstruction::Assign:
    case IRInstruction::TypeConvert:
    case IRInstruction::Return:
        return 1;
    default:
        return 1;
    }
}

// Приводит имя к безопасному идентификатору для файлов, функций и типов C.
QString sanitizeIdentifier(const QString &value)
{
    QString result = value.toLower();
    for (QChar &ch : result) {
        if (!ch.isLetterOrNumber())
            ch = '_';
    }
    while (result.contains("__"))
        result.replace("__", "_");
    result = result.trimmed();
    if (result.startsWith('_'))
        result.remove(0, 1);
    if (result.isEmpty())
        result = "submodule";
    if (result.front().isDigit())
        result.prepend("m_");
    return result;
}

// Формирует banner для generated-файла, чтобы пользователь видел origin графа и роль файла.
QString makeGeneratedGraphBanner(const Graph &graph, const QString &role)
{
    QString banner;
    QTextStream out(&banner);
    out << "// Generated by DeltaQ IDE.\n";
    out << "// Source: graph '" << graph.name << "'";
    if (!graph.id.isEmpty())
        out << " (id: " << graph.id << ")";
    out << "\n";
    out << "// File role: " << role << "\n";
    out << "// Warning: this file is generated and may be overwritten.\n\n";
    return banner;
}

QString joinFunctionArguments(const QStringList &args)
{
    return args.isEmpty() ? QString("void") : args.join(", ");
}

} // namespace

GraphCompiler::GraphCompiler(ModuleRegistry *registry)
    : m_registry(registry)
{
}

// Формирует стабильное имя файлов generated подмодуля, чтобы root graph мог
// подключать header независимо от внутреннего имени графа.
QString GraphCompiler::submoduleFileBaseName(const Module &mod) const
{
    // Если пользователь явно задал имя generated-файлов, используем именно его.
    if (!mod.generatedFileBaseName.trimmed().isEmpty())
        return sanitizeIdentifier(mod.generatedFileBaseName);

    // Для старых подмодулей без отдельного file base оставляем совместимый fallback.
    return sanitizeIdentifier(mod.name) + "_" + mod.id.left(8);
}

// Имя callable-функции, через которую родительский граф обращается к подмодулю.
QString GraphCompiler::submoduleFunctionName(const Module &mod) const
{
    return "dq_sub_" + submoduleFileBaseName(mod);
}

// Имя result-структуры для составного модуля с несколькими data-выходами.
QString GraphCompiler::submoduleResultTypeName(const Module &mod) const
{
    return "dq_sub_" + submoduleFileBaseName(mod) + "_result";
}

CompilationResult GraphCompiler::compile(const Graph &graph)
{
    CompilationResult result;
    m_inlineDesktopBackendDeclared = false;

    // 1. Валидация: проверяем что все модули существуют
    for (const auto &node : graph.nodes) {
        const Module *mod = m_registry->findModule(node.moduleId);
        if (!mod) {
            result.errors.append(
                QObject::tr("Node '%1': module '%2' not found in registry")
                .arg(node.id, node.moduleId));
            continue;
        }

        QString admissionReason;
        if (!m_registry->isModuleAdmittedForComposition(*mod, &admissionReason)) {
            result.errors.append(
                QObject::tr("Node '%1': module '%2' is not ready for composition: %3")
                    .arg(node.id, mod->name, admissionReason));
        }
    }

    // Проверяем, что все соединения ведут к существующим узлам и портам
    for (const auto &conn : graph.connections) {
        const auto *fromNode = graph.findNode(conn.from.nodeId);
        const auto *toNode = graph.findNode(conn.to.nodeId);

        if (!fromNode) {
            result.errors.append(
                QObject::tr("Connection: source node '%1' not found").arg(conn.from.nodeId));
            continue;
        }
        if (!toNode) {
            result.errors.append(
                QObject::tr("Connection: target node '%1' not found").arg(conn.to.nodeId));
            continue;
        }

        // Проверяем порты
        const Module *fromMod = m_registry->findModule(fromNode->moduleId);
        const Module *toMod = m_registry->findModule(toNode->moduleId);

        if (fromMod && !fromMod->hasOutput(conn.from.portName)) {
            result.errors.append(
                QObject::tr("Connection: port '%1' not found in module '%2' outputs")
                .arg(conn.from.portName, fromMod->name));
        }
        if (toMod && !toMod->hasInput(conn.to.portName)) {
            result.errors.append(
                QObject::tr("Connection: port '%1' not found in module '%2' inputs")
                .arg(conn.to.portName, toMod->name));
        }

        // Проверяем совместимость типов
        if (fromMod && toMod) {
            const Port *outPort = fromMod->findOutput(conn.from.portName);
            const Port *inPort = toMod->findInput(conn.to.portName);
            if (outPort && inPort && !areTypesCompatible(outPort->type, inPort->type)) {
                result.errors.append(
                    QObject::tr("Type mismatch: '%1' (%2) → '%3' (%4)")
                    .arg(conn.from.portName, outPort->type, conn.to.portName, inPort->type));
            }
        }
    }

    if (!result.errors.isEmpty()) {
        result.success = false;
        return result;
    }

    // 1.5. Проверка совместимости языков модулей
    QSet<QString> usedLanguages;
    for (const auto &node : graph.nodes) {
        const Module *mod = m_registry->findModule(node.moduleId);
        if (mod && !mod->language.isEmpty())
            usedLanguages.insert(mod->language);
    }
    // C и C++ совместимы, но Python/Rust — нет
    QSet<QString> incompatible = usedLanguages;
    incompatible.remove("c");
    incompatible.remove("cpp");
    if (!incompatible.isEmpty() && (usedLanguages.contains("c") || usedLanguages.contains("cpp"))) {
        for (const auto &lang : incompatible) {
            result.errors.append(
                QObject::tr("Language '%1' is not compatible with C/C++ modules in this graph")
                .arg(lang));
        }
    }

    if (!result.errors.isEmpty()) {
        result.success = false;
        return result;
    }

    // 2. Топологическая сортировка
    QStringList sortedNodes = topologicalSort(graph, result.errors);
    if (!result.errors.isEmpty()) {
        result.success = false;
        return result;
    }

    // 3. Генерация IR
    IR ir = generateIR(graph, sortedNodes, result);
    if (!result.errors.isEmpty()) {
        result.success = false;
        return result;
    }

    // 4. Генерация C-кода
    const QString banner = makeGeneratedGraphBanner(
        graph, QObject::tr("generated C source from a DeltaQ graph."));
    result.generatedCode = banner + ir.emitCCode();

    int currentLine = 1 + banner.count('\n');
    currentLine += ir.includes.size();
    if (!ir.includes.isEmpty())
        currentLine += 1;
    for (const auto &src : ir.moduleSources)
        currentLine += src.count('\n') + 2;
    currentLine += 1; // строка int main(...)

    for (const auto &instr : ir.instructions) {
        if (!instr.sourceNodeId.isEmpty()) {
            const int count = emittedLineCount(instr);
            for (int i = 0; i < count; ++i)
                result.sourceMap[currentLine + i] = instr.sourceNodeId;
            currentLine += count;
        } else {
            currentLine += emittedLineCount(instr);
        }
    }

    result.success = true;
    return result;
}

SubmoduleUnitResult GraphCompiler::compileSubmoduleUnit(const Module &module)
{
    // Генерирует отдельные .h/.c для составного модуля, чтобы он участвовал в сборке
    // как самостоятельная единица компиляции, а не разворачивался в родителя.
    SubmoduleUnitResult result;

    if (!module.isComposite()) {
        result.errors.append(QObject::tr("Module '%1' is not a composite submodule").arg(module.name));
        return result;
    }

    if (!m_graphStore) {
        result.errors.append(QObject::tr("Graph store is not attached"));
        return result;
    }

    QString admissionReason;
    if (!m_registry->isModuleAdmittedForComposition(module, &admissionReason)) {
        result.errors.append(
            QObject::tr("Module '%1' is not ready for composition: %2")
                .arg(module.name, admissionReason));
        return result;
    }

    const Graph *innerGraph = m_graphStore->findGraph(module.graphId);
    if (!innerGraph) {
        result.errors.append(
            QObject::tr("Inner graph '%1' was not found for module '%2'")
                .arg(module.graphId, module.name));
        return result;
    }

    CompilationResult graphResult;
    const QStringList sortedNodes = topologicalSort(*innerGraph, graphResult.errors);
    if (!graphResult.errors.isEmpty()) {
        result.errors = graphResult.errors;
        return result;
    }

    QStringList functionArgs;
    QMap<QString, QString> inputOverrides;

    // Внешние data-входы становятся параметрами generated функции подмодуля.
    for (const auto &input : module.inputs) {
        if (input.kind == PortKind::Execution)
            continue;

        const CompositePortBinding *binding = module.findBoundaryInput(input.name);
        if (!binding) {
            result.errors.append(
                QObject::tr("Submodule '%1' is missing boundary input mapping for '%2'")
                    .arg(module.name, input.name));
            return result;
        }

        const QString argName = sanitizeIdentifier(input.name);
        functionArgs.append(QString("%1 %2").arg(toCType(input.type), argName));
        inputOverrides.insert(binding->internalNodeId + ":" + binding->internalPortName, argName);
    }

    QMap<QString, QString> portVarMap;
    IR ir = generateIR(*innerGraph, sortedNodes, graphResult, &portVarMap, inputOverrides);
    if (!graphResult.errors.isEmpty()) {
        result.errors = graphResult.errors;
        return result;
    }

    const QString fileBase = submoduleFileBaseName(module);
    const QString functionName = submoduleFunctionName(module);
    const QString resultTypeName = submoduleResultTypeName(module);
    result.fileBaseName = fileBase;
    result.functionName = functionName;

    QVector<Port> dataOutputs;
    for (const auto &output : module.outputs) {
        if (output.kind == PortKind::Data)
            dataOutputs.append(output);
    }

    QString returnType = "void";
    if (dataOutputs.size() == 1)
        returnType = toCType(dataOutputs.first().type);
    else if (dataOutputs.size() > 1)
        returnType = resultTypeName;

    const QString headerGuard = sanitizeIdentifier(fileBase).toUpper() + "_H";
    const QString signature = QString("%1 %2(%3)")
        .arg(returnType, functionName, joinFunctionArguments(functionArgs));

    QString header;
    header += makeGeneratedGraphBanner(
        *innerGraph,
        QObject::tr("generated header for a DeltaQ graph module (%1).").arg(fileBase + ".h"));
    header += "#ifndef " + headerGuard + "\n";
    header += "#define " + headerGuard + "\n\n";
    for (const auto &inc : ir.includes)
        header += QString("#include %1\n").arg(inc);
    if (!ir.includes.isEmpty())
        header += "\n";

    if (dataOutputs.size() > 1) {
        header += "typedef struct " + resultTypeName + " {\n";
        for (const auto &output : dataOutputs)
            header += QString("    %1 %2;\n").arg(toCType(output.type), output.name);
        header += "} " + resultTypeName + ";\n\n";
    }

    header += signature + ";\n\n";
    header += "#endif\n";
    result.headerCode = header;

    QString source;
    source += makeGeneratedGraphBanner(
        *innerGraph,
        QObject::tr("generated implementation for a DeltaQ graph module (%1).")
            .arg(fileBase + ".c"));
    source += QString("#include \"generated/submodules/%1.h\"\n").arg(fileBase);
    source += "\n";
    for (const auto &src : ir.moduleSources)
        source += src + "\n\n";
    source += signature + " {\n";
    source += ir.emitBodyCode(1);

    if (dataOutputs.isEmpty()) {
        source += "}\n";
        result.sourceCode = source;
        result.success = true;
        return result;
    }

    if (dataOutputs.size() == 1) {
        const CompositePortBinding *binding = module.findBoundaryOutput(dataOutputs.first().name);
        if (!binding) {
            result.errors.append(
                QObject::tr("Submodule '%1' is missing boundary output mapping for '%2'")
                    .arg(module.name, dataOutputs.first().name));
            return result;
        }

        const QString sourceKey = binding->internalNodeId + ":" + binding->internalPortName;
        const QString valueExpr = portVarMap.value(sourceKey);
        if (valueExpr.isEmpty()) {
            result.errors.append(
                QObject::tr("Submodule '%1' could not resolve output value for '%2'")
                    .arg(module.name, dataOutputs.first().name));
            return result;
        }

        source += QString("    return %1;\n").arg(valueExpr);
        source += "}\n";
        result.sourceCode = source;
        result.success = true;
        return result;
    }

    source += QString("    %1 result_value;\n").arg(resultTypeName);
    for (const auto &output : dataOutputs) {
        const CompositePortBinding *binding = module.findBoundaryOutput(output.name);
        if (!binding) {
            result.errors.append(
                QObject::tr("Submodule '%1' is missing boundary output mapping for '%2'")
                    .arg(module.name, output.name));
            return result;
        }

        const QString sourceKey = binding->internalNodeId + ":" + binding->internalPortName;
        const QString valueExpr = portVarMap.value(sourceKey);
        if (valueExpr.isEmpty()) {
            result.errors.append(
                QObject::tr("Submodule '%1' could not resolve output value for '%2'")
                    .arg(module.name, output.name));
            return result;
        }
        source += QString("    result_value.%1 = %2;\n").arg(output.name, valueExpr);
    }
    source += "    return result_value;\n";
    source += "}\n";

    result.sourceCode = source;
    result.success = true;
    return result;
}

QStringList GraphCompiler::topologicalSort(const Graph &graph, QStringList &errors)
{
    // Проверяем наличие execution-связей
    bool hasExecConnections = false;
    for (const auto &conn : graph.connections) {
        if (conn.kind == PortKind::Execution) {
            hasExecConnections = true;
            break;
        }
    }

    // Если есть exec-связи — используем exec-aware сортировку
    if (hasExecConnections)
        return topologicalSortByExecution(graph, errors);

    // Иначе — обычная data flow сортировка (обратная совместимость)
    return topologicalSortByData(graph, errors);
}

QStringList GraphCompiler::topologicalSortByData(const Graph &graph, QStringList &errors)
{
    // Построение графа зависимостей: для каждого узла — от каких узлов он зависит
    QMap<QString, QSet<QString>> deps;  // nodeId → множество зависимостей
    QMap<QString, QSet<QString>> rdeps; // nodeId → кто от него зависит

    for (const auto &node : graph.nodes) {
        deps[node.id] = {};
        rdeps[node.id] = {};
    }

    for (const auto &conn : graph.connections) {
        if (conn.kind == PortKind::Execution)
            continue; // Игнорируем exec-связи для data-сортировки
        deps[conn.to.nodeId].insert(conn.from.nodeId);
        rdeps[conn.from.nodeId].insert(conn.to.nodeId);
    }

    // Алгоритм Кана
    QStringList result;
    QStringList queue;

    for (auto it = deps.begin(); it != deps.end(); ++it) {
        if (it.value().isEmpty())
            queue.append(it.key());
    }

    while (!queue.isEmpty()) {
        QString nodeId = queue.takeFirst();
        result.append(nodeId);

        for (const auto &dependent : rdeps[nodeId]) {
            deps[dependent].remove(nodeId);
            if (deps[dependent].isEmpty())
                queue.append(dependent);
        }
    }

    if (result.size() != graph.nodes.size()) {
        errors.append(QObject::tr("Cycle detected in graph — cannot compile"));
    }

    return result;
}

QStringList GraphCompiler::topologicalSortByExecution(const Graph &graph, QStringList &errors)
{
    // Строим граф data-зависимостей (без exec-связей)
    QMap<QString, QSet<QString>> dataDeps;
    for (const auto &node : graph.nodes)
        dataDeps[node.id] = {};

    for (const auto &conn : graph.connections) {
        if (conn.kind != PortKind::Execution)
            dataDeps[conn.to.nodeId].insert(conn.from.nodeId);
    }

    // Строим exec-граф: exec-зависимости
    QMap<QString, QSet<QString>> execDeps;   // nodeId → входящие exec-связи
    QMap<QString, QStringList> execNext;     // nodeId → исходящие exec-связи (в порядке)
    for (const auto &node : graph.nodes) {
        execDeps[node.id] = {};
    }
    for (const auto &conn : graph.connections) {
        if (conn.kind == PortKind::Execution) {
            execDeps[conn.to.nodeId].insert(conn.from.nodeId);
            execNext[conn.from.nodeId].append(conn.to.nodeId);
        }
    }

    // Находим стартовые exec-узлы (участвуют в exec-связях, но без входящих exec)
    QStringList execStarts;
    QSet<QString> execParticipants;
    for (const auto &conn : graph.connections) {
        if (conn.kind == PortKind::Execution) {
            execParticipants.insert(conn.from.nodeId);
            execParticipants.insert(conn.to.nodeId);
        }
    }
    for (const auto &nodeId : execParticipants) {
        if (execDeps[nodeId].isEmpty())
            execStarts.append(nodeId);
    }

    QStringList result;
    QSet<QString> visited;

    // Обходим exec-цепочку — перед каждым узлом вставляем его data-зависимости
    QStringList execQueue = execStarts;
    QSet<QString> execProcessed;

    while (!execQueue.isEmpty()) {
        QString nodeId = execQueue.takeFirst();
        if (execProcessed.contains(nodeId))
            continue;
        execProcessed.insert(nodeId);

        // Вставляем data-зависимости рекурсивно
        insertWithDataDeps(nodeId, graph, visited, result, dataDeps);

        // Следуем по exec-выходам
        for (const auto &next : execNext[nodeId])
            execQueue.append(next);
    }

    // Добавляем оставшиеся data-only узлы (не участвующие в exec-flow)
    QStringList remainingErrors;
    QStringList dataOnly = topologicalSortByData(graph, remainingErrors);
    for (const auto &nodeId : dataOnly) {
        if (!visited.contains(nodeId)) {
            visited.insert(nodeId);
            result.append(nodeId);
        }
    }

    if (result.size() != graph.nodes.size()) {
        errors.append(QObject::tr("Cycle detected in graph — cannot compile"));
    }

    return result;
}

void GraphCompiler::insertWithDataDeps(const QString &nodeId, const Graph &graph,
                                        QSet<QString> &visited, QStringList &result,
                                        const QMap<QString, QSet<QString>> &dataDeps)
{
    if (visited.contains(nodeId))
        return;

    // Сначала вставляем все data-зависимости
    for (const auto &dep : dataDeps[nodeId]) {
        Q_UNUSED(graph)
        insertWithDataDeps(dep, graph, visited, result, dataDeps);
    }

    visited.insert(nodeId);
    result.append(nodeId);
}

IR GraphCompiler::generateIR(const Graph &graph, const QStringList &sortedNodes,
                              CompilationResult &result,
                              QMap<QString, QString> *generatedPortVarMap,
                              const QMap<QString, QString> &inputOverrides)
{
    IR ir;
    ir.addInclude("<stdio.h>");

    // Сбор уникальных модулей — дедупликация includes и определений
    QSet<QString> processedModuleIds;
    QSet<QString> processedModuleSources;
    for (const auto &node : graph.nodes) {
        if (processedModuleIds.contains(node.moduleId))
            continue;
        processedModuleIds.insert(node.moduleId);

        const Module *mod = m_registry->findModule(node.moduleId);
        if (!mod) continue;

        // Собираем includes модуля
        for (const auto &inc : mod->includes) {
            QString header = inc;
            if (!header.startsWith('<') && !header.startsWith('"'))
                header = QString("<%1>").arg(inc);
            ir.addInclude(header);
        }

        // Собираем sourceCode модуля (определение функции)
        if (!mod->sourceCode.isEmpty() &&
            !isInlineDesktopModule(mod->id) &&
            !processedModuleSources.contains(mod->sourceCode)) {
            processedModuleSources.insert(mod->sourceCode);
            ir.moduleSources.append(mod->sourceCode);
        }
    }

    // Маппинг: nodeId:portName → имя переменной в C-коде
    QMap<QString, QString> portVarMap;

    for (const auto &nodeId : sortedNodes) {
        const GraphNode *node = graph.findNode(nodeId);
        if (!node) continue;

        const Module *mod = m_registry->findModule(node->moduleId);
        if (!mod) continue;

        ir.addInstruction(IRInstruction::makeComment(
            QObject::tr("Node: %1 (%2)").arg(mod->name, nodeId.left(8))));

        const bool inlineDesktop = isInlineDesktopModule(mod->id);
        const QString sanitizedNodeId = QString(nodeId).replace('-', '_');

        // Объявляем переменные для output-портов (пропускаем exec-порты)
        for (const auto &outPort : mod->outputs) {
            if (outPort.kind == PortKind::Execution)
                continue;
            QString varName = QString("var_%1_%2").arg(
                sanitizedNodeId,
                outPort.name);
            QString cType = toCType(outPort.type);

            portVarMap[nodeId + ":" + outPort.name] = varName;
            if (!inlineDesktop) {
                ir.addInstruction(IRInstruction::makeDeclareVar(varName, cType, nodeId));
                ir.declareVariable(varName, cType);
            }
        }

        // Подготавливаем аргументы (входные порты, пропускаем exec-порты)
        QStringList callArgs;
        for (const auto &inPort : mod->inputs) {
            if (inPort.kind == PortKind::Execution)
                continue;
            QString argValue;
            bool found = false;

            // Ищем входящее соединение для этого порта
            for (const auto &conn : graph.connections) {
                if (conn.to.nodeId == nodeId && conn.to.portName == inPort.name) {
                    QString sourceKey = conn.from.nodeId + ":" + conn.from.portName;
                    argValue = portVarMap.value(sourceKey);

                    // Проверяем необходимость конверсии типа
                    const GraphNode *srcNode = graph.findNode(conn.from.nodeId);
                    if (srcNode) {
                        const Module *srcMod = m_registry->findModule(srcNode->moduleId);
                        if (srcMod) {
                            const Port *srcPort = srcMod->findOutput(conn.from.portName);
                            if (srcPort && needsTypeConversion(srcPort->type, inPort.type)) {
                                QString convertedVar = argValue + "_conv";
                                QString cType = toCType(inPort.type);
                                ir.addInstruction(IRInstruction::makeTypeConvert(
                                    convertedVar, argValue, cType, nodeId));
                                ir.declareVariable(convertedVar, cType);
                                argValue = convertedVar;
                            }
                        }
                    }

                    found = true;
                    break;
                }
            }

            if (!found) {
                const QString overrideKey = nodeId + ":" + inPort.name;
                if (inputOverrides.contains(overrideKey)) {
                    // Для подмодуля внешний input связывается с конкретным внутренним портом.
                    argValue = inputOverrides.value(overrideKey);
                } else {
                    // Используем значение из свойств узла или значение по умолчанию
                    argValue = node->properties.value(
                        inPort.name,
                        inPort.defaultValue.isEmpty() ? "0" : inPort.defaultValue);
                }
            }

            callArgs.append(argValue);
        }

        QVector<Port> dataOutputs = mod->dataOutputs();
        const QString firstDataOutputName = dataOutputs.isEmpty() ? QString() : dataOutputs.first().name;

        // Генерируем вызов функции
        if (inlineDesktop) {
            if (!emitInlineDesktopModuleIR(*node, *mod, callArgs, portVarMap, ir, result))
                result.errors.append(QObject::tr("Failed to emit desktop runtime node '%1'").arg(mod->name));
        } else if (UIModuleFactory::isUIContractModule(*mod) ||
                   UIModuleFactory::isUIModule(node->moduleId) ||
                   UIModuleFactory::isUIModuleByName(mod->name)) {
            // Stage 1: UI-модули трактуются как backend-независимый контракт.
            // Конкретный runtime/render код по-прежнему генерируется backend-слоем.
            const QString widgetType = UIModuleFactory::widgetType(*mod);
            const QString readableType = widgetType.isEmpty() ? mod->name : widgetType;
            ir.addInstruction(IRInstruction::makeComment(
                QString("UI contract: %1").arg(readableType)));

            QSet<QString> eventOutputs;
            for (const auto &value : mod->metadata.value("deltaq.ui.events").toArray())
                eventOutputs.insert(value.toString());

            QMap<QString, int> inputIndexes;
            for (int i = 0; i < mod->inputs.size(); ++i)
                inputIndexes.insert(mod->inputs[i].name, i);

            // Для UI-контрактов данные выходов выводим из одноимённых входов/состояния,
            // а signal-выходы оставляем placeholder-ами до runtime wiring.
            for (const auto &outPort : mod->outputs) {
                const QString targetVar = portVarMap.value(nodeId + ":" + outPort.name);
                if (targetVar.isEmpty())
                    continue;

                if (eventOutputs.contains(outPort.name) || outPort.type == "signal") {
                    ir.addInstruction(IRInstruction::makeAssign(
                        targetVar, "0 /* ui contract event placeholder */", nodeId));
                    continue;
                }

                QString sourceValue;
                if (inputIndexes.contains(outPort.name)) {
                    sourceValue = callArgs.value(inputIndexes.value(outPort.name));
                } else if (outPort.name == "value" && inputIndexes.contains("text")) {
                    sourceValue = callArgs.value(inputIndexes.value("text"));
                }

                if (!sourceValue.isEmpty()) {
                    ir.addInstruction(IRInstruction::makeAssign(
                        targetVar, sourceValue, nodeId));
                }
            }
        } else if (mod->isComposite() && m_graphStore) {
            // Композитный подмодуль подключается как отдельная единица компиляции через header.
            const QString subHeader = QString("\"generated/submodules/%1.h\"")
                                          .arg(submoduleFileBaseName(*mod));
            ir.addInclude(subHeader);

            QString subFuncName = compileSubModule(*mod, result);
            if (!subFuncName.isEmpty()) {
                if (dataOutputs.isEmpty()) {
                    ir.addInstruction(IRInstruction::makeCall({}, subFuncName, callArgs, nodeId));
                } else if (dataOutputs.size() == 1) {
                    const QString targetVar = portVarMap.value(nodeId + ":" + firstDataOutputName);
                    ir.addInstruction(IRInstruction::makeCall(targetVar, subFuncName, callArgs, nodeId));
                } else {
                    const QString resultVar = QString("var_%1_sub_result").arg(sanitizedNodeId);
                    const QString resultType = submoduleResultTypeName(*mod);
                    ir.addInstruction(IRInstruction::makeDeclareVar(resultVar, resultType, nodeId));
                    ir.declareVariable(resultVar, resultType);
                    ir.addInstruction(IRInstruction::makeCall(resultVar, subFuncName, callArgs, nodeId));
                    for (const auto &outPort : dataOutputs) {
                        const QString targetVar = portVarMap.value(nodeId + ":" + outPort.name);
                        ir.addInstruction(IRInstruction::makeAssign(
                            targetVar,
                            QString("%1.%2").arg(resultVar, outPort.name),
                            nodeId));
                    }
                }
            }
        } else {
            // Обычный модуль
            QString funcName = QString("dq_%1").arg(mod->name.toLower().replace(' ', '_'));

            if (firstDataOutputName.isEmpty()) {
                // Функция без возвращаемого значения
                ir.addInstruction(IRInstruction::makeCall({}, funcName, callArgs, nodeId));
            } else {
                // Функция с возвращаемым значением
                QString targetVar = portVarMap.value(nodeId + ":" + firstDataOutputName);
                ir.addInstruction(IRInstruction::makeCall(targetVar, funcName, callArgs, nodeId));
            }
        }
    }

    if (generatedPortVarMap)
        *generatedPortVarMap = portVarMap;
    return ir;
}

bool GraphCompiler::isInlineDesktopModule(const QString &moduleId) const
{
    static const QSet<QString> inlineModules = {
        "core.desktop.sdl_init",
        "core.desktop.ttf_init",
        "core.desktop.create_window",
        "core.desktop.create_renderer",
        "core.desktop.ui_init",
        "core.desktop.event_loop",
        "core.desktop.ui_cleanup_font",
        "core.desktop.destroy_renderer",
        "core.desktop.destroy_window",
        "core.desktop.ttf_quit",
        "core.desktop.sdl_quit"
    };

    return inlineModules.contains(moduleId);
}

QString GraphCompiler::inlineDesktopBackendContextName() const
{
    return "dq_ui_backend_ctx";
}

void GraphCompiler::ensureInlineDesktopBackendContext(IR &ir, const QString &nodeId)
{
    if (m_inlineDesktopBackendDeclared)
        return;

    // Inline desktop runtime опирается на generated UI backend boundary из ui/window1.h.
    ir.addInclude("\"ui/window1.h\"");
    ir.addInstruction(IRInstruction::makeRawCode(
        QString("DQ_UIBackendContext %1 = {0};").arg(inlineDesktopBackendContextName()),
        nodeId));
    m_inlineDesktopBackendDeclared = true;
}

bool GraphCompiler::emitInlineDesktopModuleIR(const GraphNode &node, const Module &mod,
                                              const QStringList &callArgs,
                                              const QMap<QString, QString> &portVarMap,
                                              IR &ir, CompilationResult &result)
{
    const auto outputVar = [&](const QString &portName) {
        return portVarMap.value(node.id + ":" + portName);
    };
    const QString backendCtx = inlineDesktopBackendContextName();

    if (mod.id == "core.desktop.sdl_init") {
        ensureInlineDesktopBackendContext(ir, node.id);
        ir.addInstruction(IRInstruction::makeComment(
            "Desktop backend lifecycle будет инициализирован через dq_ui_backend_init в create_window."));
        return true;
    }

    if (mod.id == "core.desktop.ttf_init") {
        ensureInlineDesktopBackendContext(ir, node.id);
        ir.addInstruction(IRInstruction::makeComment(
            "Text backend инициализируется внутри dq_ui_backend_init."));
        return true;
    }

    if (mod.id == "core.desktop.create_window") {
        ensureInlineDesktopBackendContext(ir, node.id);
        const QString windowVar = outputVar("window");
        if (windowVar.isEmpty()) {
            result.errors.append(QObject::tr("Desktop module '%1' requires 'window' output")
                                 .arg(mod.name));
            return false;
        }

        ir.addInstruction(IRInstruction::makeRawCode(
            QString(
                "if (!dq_ui_backend_init(&%1, %2, %3, %4)) {\n"
                "    return 1;\n"
                "}\n"
                "SDL_Window *%5 = dq_ui_backend_window(&%1);\n"
                "if (!%5) {\n"
                "    dq_ui_backend_shutdown(&%1);\n"
                "    return 1;\n"
                "}")
                .arg(backendCtx,
                     callArgs.value(0, "\"window1\""),
                     callArgs.value(1, "640"),
                     callArgs.value(2, "480"),
                     windowVar),
            node.id));
        return true;
    }

    if (mod.id == "core.desktop.create_renderer") {
        ensureInlineDesktopBackendContext(ir, node.id);
        const QString rendererVar = outputVar("renderer");
        if (rendererVar.isEmpty()) {
            result.errors.append(QObject::tr("Desktop module '%1' requires 'renderer' output")
                                 .arg(mod.name));
            return false;
        }

        ir.addInstruction(IRInstruction::makeRawCode(
            QString(
                "SDL_Renderer *%1 = dq_ui_backend_renderer(&%2);\n"
                "if (!%1) {\n"
                "    fprintf(stderr, \"Desktop backend renderer is not available\\n\");\n"
                "    dq_ui_backend_shutdown(&%2);\n"
                "    return 1;\n"
                "}")
                .arg(rendererVar, backendCtx),
            node.id));
        return true;
    }

    if (mod.id == "core.desktop.ui_init") {
        const QString uiVar = outputVar("ui_state");
        if (uiVar.isEmpty()) {
            result.errors.append(QObject::tr("Desktop module '%1' requires 'ui_state' output")
                                 .arg(mod.name));
            return false;
        }

        ir.addInstruction(IRInstruction::makeRawCode(
            QString("UIState %1;\nui_init(&%1);").arg(uiVar),
            node.id));
        return true;
    }

    if (mod.id == "core.desktop.event_loop") {
        ensureInlineDesktopBackendContext(ir, node.id);
        ir.addInstruction(IRInstruction::makeRawCode(
            QString(
                "bool running = true;\n"
                "DQ_UIBackendEvent event;\n"
                "DQ_UIRuntimeEvent runtime_event;\n"
                "int window_width = 0;\n"
                "int window_height = 0;\n"
                "Uint32 last_tick = dq_ui_backend_ticks();\n"
                "\n"
                "while (running) {\n"
                "    while (dq_ui_backend_poll_event(&event)) {\n"
                "        if (!dq_ui_backend_translate_event(&event, &runtime_event)) {\n"
                "            continue;\n"
                "        }\n"
                "        if (runtime_event.kind == DQ_UIRuntimeEvent_Quit) {\n"
                "            running = false;\n"
                "            break;\n"
                "        }\n"
                "        ui_handle_event(&%1, &runtime_event);\n"
                "    }\n"
                "\n"
                "    Uint32 now = dq_ui_backend_ticks();\n"
                "    ui_update(&%1, now - last_tick);\n"
                "    last_tick = now;\n"
                "\n"
                "    dq_ui_backend_window_size(&%3, &window_width, &window_height);\n"
                "    ui_apply_layout(&%1, window_width, window_height);\n"
                "    dq_ui_backend_begin_frame(&%3);\n"
                "    ui_render(&%1, %2);\n"
                "    dq_ui_backend_end_frame(&%3);\n"
                "}")
                .arg(callArgs.value(1, "ui"),
                     callArgs.value(0, "renderer"),
                     backendCtx),
            node.id));
        return true;
    }

    if (mod.id == "core.desktop.ui_cleanup_font") {
        ir.addInstruction(IRInstruction::makeRawCode(
            QString("if (%1.font) TTF_CloseFont(%1.font);")
                .arg(callArgs.value(0, "ui")),
            node.id));
        return true;
    }

    if (mod.id == "core.desktop.destroy_renderer") {
        ensureInlineDesktopBackendContext(ir, node.id);
        ir.addInstruction(IRInstruction::makeRawCode(
            QString("dq_ui_backend_release_renderer(&%1);").arg(backendCtx),
            node.id));
        return true;
    }

    if (mod.id == "core.desktop.destroy_window") {
        ensureInlineDesktopBackendContext(ir, node.id);
        ir.addInstruction(IRInstruction::makeRawCode(
            QString("dq_ui_backend_release_window(&%1);").arg(backendCtx),
            node.id));
        return true;
    }

    if (mod.id == "core.desktop.ttf_quit") {
        ir.addInstruction(IRInstruction::makeComment(
            "Text backend shutdown выполняется через dq_ui_backend_shutdown."));
        return true;
    }

    if (mod.id == "core.desktop.sdl_quit") {
        ensureInlineDesktopBackendContext(ir, node.id);
        ir.addInstruction(IRInstruction::makeRawCode(
            QString("dq_ui_backend_shutdown(&%1);").arg(backendCtx),
            node.id));
        return true;
    }

    result.errors.append(QObject::tr("Unsupported desktop runtime module: '%1'").arg(mod.id));
    return false;
}

QString GraphCompiler::compileSubModule(const Module &mod, CompilationResult &result)
{
    const QString funcName = submoduleFunctionName(mod);
    if (m_compiledSubModules.contains(mod.id))
        return funcName;
    m_compiledSubModules.insert(mod.id);

    if (!m_graphStore || !m_graphStore->findGraph(mod.graphId)) {
        result.errors.append(
            QObject::tr("Подмодуль '%1': внутренний граф '%2' не найден")
                .arg(mod.name, mod.graphId));
        return {};
    }

    // Реальная генерация отдельного .h/.c выполняется в PreBuildProcessor.
    // Здесь компилятору родительского графа достаточно знать имя callable-функции.
    return funcName;
}

bool GraphCompiler::areTypesCompatible(const QString &from, const QString &to) const
{
    if (from == to) return true;

    // Exec-тип совместим только с exec
    if (from == "exec" || to == "exec") return false;

    // Неявные преобразования
    if (from == "int" && (to == "float" || to == "double")) return true;
    if (from == "float" && to == "double") return true;
    if (from == "bool" && to == "int") return true;

    return false;
}

bool GraphCompiler::needsTypeConversion(const QString &from, const QString &to) const
{
    return from != to && areTypesCompatible(from, to);
}

QString GraphCompiler::toCType(const QString &portType) const
{
    if (portType == "int")    return "int";
    if (portType == "float")  return "float";
    if (portType == "double") return "double";
    if (portType == "bool")   return "int"; // C не имеет bool без stdbool.h
    if (portType == "string") return "const char*";
    if (portType == "pointer") return "void *";
    if (portType == "sdl_window") return "SDL_Window *";
    if (portType == "sdl_renderer") return "SDL_Renderer *";
    if (portType == "ui_state") return "UIState";
    return "int"; // fallback
}

} // namespace DeltaQ
