#include <QFile>
#include <QLabel>
#include <QPushButton>
#include <QSignalSpy>
#include <QTabWidget>
#include <QTemporaryDir>
#include <QTest>

#include "../../src/core/CommandBus.h"
#include "../../src/core/ModuleRegistry.h"
#include "../../src/editor/CodeEditorTab.h"
#include "../../src/editor/CodeEditorWidget.h"

using namespace DeltaQ;

class TestGeneratedFileNavigation : public QObject {
    Q_OBJECT

private:
    static QString writeFile(const QString &dirPath, const QString &fileName, const QString &content)
    {
        const QString path = dirPath + "/" + fileName;
        QFile file(path);
        if (!file.open(QIODevice::WriteOnly | QIODevice::Text))
            return {};
        file.write(content.toUtf8());
        file.close();
        return path;
    }

private slots:
    void generatedFilesAreMarkedInEditorTabs()
    {
        QTemporaryDir tmpDir;
        QVERIFY(tmpDir.isValid());

        const QString path = writeFile(
            tmpDir.path(),
            "main.c",
            "// Generated by DeltaQ IDE.\n"
            "// Source: graph 'main'\n"
            "// File role: generated C source from a DeltaQ graph.\n"
            "// Warning: this file is generated and may be overwritten.\n\n"
            "int main(void) { return 0; }\n");
        QVERIFY(!path.isEmpty());

        CommandBus bus;
        ModuleRegistry registry;
        CodeEditorWidget editor(&bus, &registry);
        editor.openFile(path);

        auto *tabs = editor.findChild<QTabWidget *>();
        QVERIFY(tabs != nullptr);
        QCOMPARE(tabs->count(), 1);
        QCOMPARE(tabs->tabText(0), QString("main.c [gen]"));
        QVERIFY(tabs->tabToolTip(0).contains("Generated by DeltaQ IDE"));
        QVERIFY(tabs->tabToolTip(0).contains("Read-only generated file"));
        QVERIFY(tabs->tabToolTip(0).contains("Source: graph 'main'"));
        QVERIFY(tabs->tabToolTip(0).contains("Edit the source-of-truth instead."));
        QVERIFY(editor.currentTab()->property("deltaqGenerated").toBool());
        QCOMPARE(editor.currentTab()->property("deltaqGeneratedSourceKind").toString(), QString("graph"));
        QCOMPARE(editor.currentTab()->property("deltaqGeneratedSourceName").toString(), QString("main"));
        QVERIFY(editor.currentTab()->editor()->isReadOnly());

        auto *banner = editor.findChild<QWidget *>("generatedOriginBanner");
        auto *bannerLabel = editor.findChild<QLabel *>("generatedOriginLabel");
        auto *bannerButton = editor.findChild<QPushButton *>("generatedOriginButton");
        QVERIFY(banner != nullptr);
        QVERIFY(bannerLabel != nullptr);
        QVERIFY(bannerButton != nullptr);
        QVERIFY(!banner->isHidden());
        QVERIFY(bannerButton->isEnabled());
        QVERIFY(bannerLabel->text().contains("Read-only generated file."));
        QVERIFY(bannerLabel->text().contains("Source of truth: graph 'main'"));

        QSignalSpy originSpy(&editor, &CodeEditorWidget::openGeneratedOriginRequested);
        bannerButton->click();
        QCOMPARE(originSpy.count(), 1);

        QSignalSpy saveSpy(&editor, &CodeEditorWidget::fileSaved);
        editor.saveCurrentFile();
        QCOMPARE(saveSpy.count(), 0);
    }

    void regularFilesStayUnmarked()
    {
        QTemporaryDir tmpDir;
        QVERIFY(tmpDir.isValid());

        const QString path = writeFile(
            tmpDir.path(),
            "manual.c",
            "int main(void) { return 0; }\n");
        QVERIFY(!path.isEmpty());

        CommandBus bus;
        ModuleRegistry registry;
        CodeEditorWidget editor(&bus, &registry);
        editor.openFile(path);

        auto *tabs = editor.findChild<QTabWidget *>();
        QVERIFY(tabs != nullptr);
        QCOMPARE(tabs->count(), 1);
        QCOMPARE(tabs->tabText(0), QString("manual.c"));
        QVERIFY(!tabs->tabToolTip(0).contains("Generated by DeltaQ IDE"));
        QVERIFY(!editor.currentTab()->property("deltaqGenerated").toBool());
        QVERIFY(!editor.currentTab()->editor()->isReadOnly());
        auto *banner = editor.findChild<QWidget *>("generatedOriginBanner");
        QVERIFY(banner != nullptr);
        QVERIFY(banner->isHidden());

        QSignalSpy saveSpy(&editor, &CodeEditorWidget::fileSaved);
        editor.saveCurrentFile();
        QCOMPARE(saveSpy.count(), 1);
    }
};

QTEST_MAIN(TestGeneratedFileNavigation)
#include "test_GeneratedFileNavigation.moc"
