#include <QFile>
#include <QSignalSpy>
#include <QTemporaryDir>
#include <QTest>

#include "../../src/editor/ProjectTreeView.h"

using namespace DeltaQ;

class TestProjectTreeView : public QObject {
    Q_OBJECT

private:
    static QString writeFile(const QString &path, const QString &content)
    {
        QFile file(path);
        if (!file.open(QIODevice::WriteOnly | QIODevice::Text))
            return {};
        file.write(content.toUtf8());
        file.close();
        return path;
    }

private slots:
    void detectsGeneratedGraphSources()
    {
        QTemporaryDir tmpDir;
        QVERIFY(tmpDir.isValid());

        QDir root(tmpDir.path());
        QVERIFY(root.mkpath("src"));
        QVERIFY(root.mkpath("graphs"));

        const QString graphPath = writeFile(
            root.filePath("graphs/main.dqgraph"),
            "{ \"id\": \"graph-main\", \"name\": \"main\", \"nodes\": [], \"connections\": [] }\n");
        const QString generatedPath = writeFile(
            root.filePath("src/main.c"),
            "// Generated by DeltaQ IDE.\n"
            "// Source: graph 'main'\n"
            "// File role: generated C source from a DeltaQ graph.\n"
            "// Warning: this file is generated and may be overwritten.\n\n"
            "int main(void) { return 0; }\n");
        const QString manualPath = writeFile(
            root.filePath("src/manual.c"),
            "int main(void) { return 0; }\n");

        QVERIFY(!graphPath.isEmpty());
        QVERIFY(!generatedPath.isEmpty());
        QVERIFY(!manualPath.isEmpty());

        ProjectTreeView tree;
        tree.setRootPath(tmpDir.path());

        QVERIFY(tree.isGeneratedFile(generatedPath));
        QVERIFY(!tree.isGeneratedFile(manualPath));
        QCOMPARE(tree.generatedOriginPath(generatedPath), graphPath);
        QVERIFY(tree.generatedOriginPath(manualPath).isEmpty());
    }

    void detectsGeneratedUiSources()
    {
        QTemporaryDir tmpDir;
        QVERIFY(tmpDir.isValid());

        QDir root(tmpDir.path());
        QVERIFY(root.mkpath("src/ui"));
        QVERIFY(root.mkpath("ui"));

        const QString layoutPath = writeFile(
            root.filePath("ui/window1.dqui"),
            "{ \"id\": \"layout-1\", \"name\": \"window1\", \"window\": {} }\n");
        const QString generatedHeader = writeFile(
            root.filePath("src/ui/window1.h"),
            "// Generated by DeltaQ IDE.\n"
            "// Source: UI layout 'window1'\n"
            "// File role: UI header (window1.h).\n"
            "// Warning: this file is generated and may be overwritten.\n\n"
            "#pragma once\n");

        QVERIFY(!layoutPath.isEmpty());
        QVERIFY(!generatedHeader.isEmpty());

        ProjectTreeView tree;
        tree.setRootPath(tmpDir.path());

        QVERIFY(tree.isGeneratedFile(generatedHeader));
        QCOMPARE(tree.generatedOriginPath(generatedHeader), layoutPath);
    }

    void generatedFilesOpenSourceOfTruthByDefault()
    {
        QTemporaryDir tmpDir;
        QVERIFY(tmpDir.isValid());

        QDir root(tmpDir.path());
        QVERIFY(root.mkpath("src"));
        QVERIFY(root.mkpath("graphs"));

        const QString graphPath = writeFile(
            root.filePath("graphs/main.dqgraph"),
            "{ \"id\": \"graph-main\", \"name\": \"main\", \"nodes\": [], \"connections\": [] }\n");
        const QString generatedPath = writeFile(
            root.filePath("src/main.c"),
            "// Generated by DeltaQ IDE.\n"
            "// Source: graph 'main'\n"
            "// File role: generated C source from a DeltaQ graph.\n"
            "// Warning: this file is generated and may be overwritten.\n\n"
            "int main(void) { return 0; }\n");

        QVERIFY(!graphPath.isEmpty());
        QVERIFY(!generatedPath.isEmpty());

        ProjectTreeView tree;
        tree.setRootPath(tmpDir.path());

        auto *fsModel = qobject_cast<QFileSystemModel *>(tree.model());
        QVERIFY(fsModel != nullptr);

        const QModelIndex fileIndex = fsModel->index(generatedPath);
        QVERIFY(fileIndex.isValid());

        QSignalSpy spy(&tree, &ProjectTreeView::fileSelected);
        QVERIFY(spy.isValid());

        QVERIFY(QMetaObject::invokeMethod(
            &tree,
            "onDoubleClicked",
            Qt::DirectConnection,
            Q_ARG(QModelIndex, fileIndex)));

        QCOMPARE(spy.count(), 1);
        QCOMPARE(spy.takeFirst().at(0).toString(), graphPath);
    }
};

QTEST_MAIN(TestProjectTreeView)
#include "test_ProjectTreeView.moc"
